### ISSUE TITLE
Create drupal diversity logo

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#1]
discussion about druplicon + heart
- inclusive w/o being explicitly representational

**Comment by rubyji** [comment]
Here are some new **rough drafts** for feedback based on the rainbow idea discussed today. My favorite is the third one, and it's now relatively easy for me to drop any image in as a background thanks to Bradley's pointer to the vector images.

![druplicon-rainbow1](https://cloud.githubusercontent.com/assets/5465231/19977348/a984faec-a1c9-11e6-8835-739f007e77bb.png) ![druplicon-rainbow2](https://cloud.githubusercontent.com/assets/5465231/19977350/a9861abc-a1c9-11e6-9562-6719aa961c7e.png) ![druplicon-rainbow3](https://cloud.githubusercontent.com/assets/5465231/19977351/a986e3c0-a1c9-11e6-9b36-64a116a843f3.png) ![druplicon-rainbow4](https://cloud.githubusercontent.com/assets/5465231/19977349/a9858714-a1c9-11e6-8c08-a753465e4a93.png)

**Comment by CarynEaton** [comment]
Hi all - So I played with an idea floating in my head. Not sure what I feel about it so I'll make another attempt this weekend. Told ya logos are not my speciality. ;-)
![var3](https://cloud.githubusercontent.com/assets/6156338/19993621/0eb703b0-a215-11e6-93cb-1975d976cd3c.png)
![var1](https://cloud.githubusercontent.com/assets/6156338/19993623/0ebc0c5c-a215-11e6-93df-26f960d55ba5.png)
![var2](https://cloud.githubusercontent.com/assets/6156338/19993622/0eb82c68-a215-11e6-877e-c82f324cfdfd.png)

**Comment by davidhwang** [comment]
The larger logos -- while visually pleasing at full scale -- might be a challenge to use in small contexts, i.e. profile avatars etc. due to the larger image size -- perhaps something smaller and simpler visually will read better across multiple sizes.

**Comment by davidhwang** [comment]
Also -- in general I've personally disliked the Druplicon for a very long time (cf. how rarely it's used in professional contexts, if ever) -- I'd prefer we use something more abstract and less cartoony, but that's just me.

**Comment by cleverington** [comment]
On @rubyji 

As mentioned in Slack, I believe the first three icons deviate from the overall goal of complete diversity and inclusion, which includes areas such as ADA, ethnicity, etc.

I believe your fourth Druplicon may be the coolest, but possibly wrapped in a soft-pink heart and/or a few hearts with varying colors in a ring-like orbit?

On @CarynEaton's 
Forgive the bad art (as PhotoShop isn't my best).

I agree with @davidhwang that the larger logos will make referencing visually difficult at smaller sizes (like icons). 

Maybe something along these lines?

![drupal_diversity_example2](https://cloud.githubusercontent.com/assets/1015474/20401660/565cb2d2-acbf-11e6-84f2-8168f906f7dc.png)

**Comment by CarynEaton** [comment]
Sorry all - 

I totally lost track of another round of ideas. I had the same thoughts about size and reduction on the first options too.

Here is another try - I saw the comments about the heart and ran with it. 

![druplicon-flower](https://cloud.githubusercontent.com/assets/6156338/20418312/eced26b2-ad11-11e6-8acb-3a37fefdb3da.jpg)
![drupal-love-shine](https://cloud.githubusercontent.com/assets/6156338/20418313/eced2bd0-ad11-11e6-8863-854edadca928.jpg)
![drupal-love-rainbow](https://cloud.githubusercontent.com/assets/6156338/20418314/ecee0b9a-ad11-11e6-830e-f15774225fc7.jpg)
![drupal-love](https://cloud.githubusercontent.com/assets/6156338/20418311/ececf048-ad11-11e6-9fbc-5d540c34ad06.jpg)

**Comment by CarynEaton** [comment]
Another one...

![drupal-love-background-200](https://cloud.githubusercontent.com/assets/6156338/20418343/24eafa44-ad12-11e6-9e6a-19dbeaf9338a.jpg)

**Comment by drnikko** [comment]
@CarynEaton these are awesome!  Thanks for jumping in!  There was some thumbs up for these hearts in chat.  I think we'll try to lock these down by the middle of December.  Come to our Thursday meetings (after Thanksgiving) if you can, otherwise I'm going to keep encouraging people to leave feedback here.

**Comment by rubyji** [comment]
I love Caryn's latest versions, especially the plain blue heart and the heart with starburst. The straight-up rainbow feels too specific to just LGBT to me.

**Comment by inmedimptorolta** [comment]
I can't stop loving on the plain blue heart. But let's be honest, all of them in that post rule.

**Comment by fabianx-ai** [comment]
My favorites are the hearts: Plain blue heart and the plain blue heart with the starburst.

**Comment by prestonso** [comment]
If we consider the fact that this logo may need to be used additionally as a favicon, my vote is for the plain blue heart without decoration.

**Comment by bradleyfields** [comment]
Plain blue heart. But maybe a little flatter?

**Comment by sugaroverflow** [comment]
My vote is on the plain blue heart 👍

**Comment by rpsu** [comment]
I'd go with the blue heart.

**Comment by davidhwang** [comment]
Following up from my comment in slack, I'd like to propose a dramatically simpler (visually, at least) icon that can be interpreted across a variety of contexts with minimal adaptation:

![divlogo-med](https://cloud.githubusercontent.com/assets/382095/21156462/c30d3800-c12a-11e6-9464-9ea0e90d4c48.jpg)

**Comment by rubyji** [comment]
Here are some inspired by David's (eatings) idea. BTW, I am downsizing them for posting here but the graphics I'm making are 500x500.
![druplicon-eatings1](https://cloud.githubusercontent.com/assets/5465231/21159630/f16c0850-c14f-11e6-9b61-2d426be5d5f6.png)
![druplicon-eatings2](https://cloud.githubusercontent.com/assets/5465231/21159628/f169bf00-c14f-11e6-8b58-8d4ea8afff84.png)
![druplicon-eatings3](https://cloud.githubusercontent.com/assets/5465231/21159629/f16a4b6e-c14f-11e6-981c-049c3ffd9138.png)
![druplicon-eatings4](https://cloud.githubusercontent.com/assets/5465231/21159631/f16ca35a-c14f-11e6-8b9d-d98940bbc359.png)

**Comment by peacog** [comment]
Here are a couple of ideas I had. Number 1 needs a little tweaking to fix the alignment of the drops. 
![drupal-diversity-1](https://cloud.githubusercontent.com/assets/1312689/21227988/6c030194-c2dc-11e6-8939-86cd9a0a9922.png)
![drupal-diversity-2](https://cloud.githubusercontent.com/assets/1312689/21228002/7562be46-c2dc-11e6-9ac3-7991c7708ace.png)

**Comment by mikemiles86** [comment]
Here is an Idea I had for one that represents equality. 
![drupal_equality](https://cloud.githubusercontent.com/assets/196745/21229840/e7204660-c2b0-11e6-8bb0-a6eee5431244.png)

**Comment by drnikko** [comment]
Voting on your favorite logo(s) is happening here: https://docs.google.com/forms/d/e/1FAIpQLSfyf4wza7jeqdAN8nmZe9K-9CJxf3lUQIiPaagMVcEPM7RWRQ/viewform

We'll take whatever favorites there are and focus our efforts on reworking/tweaking them. 

Thanks for all of your contributions, everyone!  I love how many of you participated and I hope you continue to participate. xo

**Comment by Grienauer** [comment]
My proposal
![drupal-diversity-logo-proposal](https://cloud.githubusercontent.com/assets/1458107/21435644/33d890a0-c87b-11e6-897f-4a0514aa4058.png)

the Drupal drop with lots of different lines which group and come together to form one shape.

and v2
![drupal-diversity-logo-proposal_2](https://cloud.githubusercontent.com/assets/1458107/21435765/c70098b4-c87b-11e6-8d62-41922752411b.png)
Now the blue lines get the exact shape of a peace sign.
If you see all colored lines as seperate "people" the blue one holds them together with his arms :)

v3 is just a variation of v2
![drupal-diversity-logo-proposal_3](https://cloud.githubusercontent.com/assets/1458107/21436051/eea12cfc-c87c-11e6-97c2-c8b75b189aab.png)
