### ISSUE TITLE
How can we fill gaps in the Drupalcon CFP

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#10]
like "what happens if your session is not chosen"

**Comment by bradleyfields** [comment]
For underrepresented folks, cost is often an issue. For a number of reasons (personal finance, doubt about whether work will support them, etc.). So, might be cool during CFP to speak to that concern however possible.

For example, contrast https://events.drupal.org/neworleans2016/news/submit-session-drupalcon-new-orleans with https://www.alterconf.com/speak.

This isn't a policy change request—not a "we must start paying people" demand. (Though, open to that conversation too.) It's a suggestion that, even without a policy change, we could help improve CFP communications so they clearly describe what is and isn't available to people who want to give sessions.

**Comment by amandagonser** [comment]
Thanks Brad.  I had popped that link into the diversity channel yesterday as a great example, so I am glad that you agree.  I definitely want to improve our communications in this sense and will be checking out additional conference CFP pages that do this well; if you have any other examples that you know of, please send them my way!

**Comment by drnikko** [comment]
HOORAY!  This is in progress.  A similar issue will probably be opened next con.
