### ISSUE TITLE
Request for Resources: "Best Practices" in Improving Diversity

### ISSUE THREAD

**Issue by jonpugh** [drupaldiversity/administration#101]
Hi. 

I'm basically just trying to collect advice on how to respond to certain things you hear when talking to event organizers or business leaders.  

I know we already have a number of resources on the website under "What can I do?" but I think I'd like to help collate all of it into a "Best Practices" guide for improving diversity & inclusion in their organization.

## What I'm looking for:
- How to make your "help-wanted" or "request for speaker" postings more welcoming in order to attract more diverse talent.
- How to make your meetups and events more welcoming, and other ways to make the attendees at my meetup more closely reflect the demographics of the city we're in.
- Good discussions or writings about real world improvements organizations have made to improve diversity, what worked, what didn't... Something practical, in writing we can point to for groups that want to improve.
- An easy-as-possible guide for people in leadership positions that leave DD&I Talks saying "Ok, I'm on board. Now what?"

## How people can contribute:

- Post links, names of books, or authors that are about 
- Contribute your own thoughts or recollections of things that worked or didn't.

## How we will use it:

- Collect even more useful things for the website's resources page.
- Put together a "Best Practices" guide to make it easier for people new to the cause to digest everything and start taking steps. 
- Refer to this guide in coversation and talks.

**Comment by davidhwang** [comment]
This problem space is so crazy huge that it's probably better to divide into two statements, each to be addressed separately.

**Comment by drnikko** [comment]
yeah - @jonpugh can we start with "how do I make the attendees at my meetup more closely reflect the demographics of the city we're in?"

**Comment by jonpugh** [comment]
Absolutely @drnikki, that seems like a good place to start.

@davidhwang yeah, it's a big challenge, and one I have no experience in solving! 

I guess I'm just seeing that advice is needed on all of the above.

**Comment by drnikko** [comment]
@jonpugh can you also update the description to:
-  be clear about what we're looking for 
- some ways that folks can contribute
- what you'll do with the contributions that people give.

**Comment by jonpugh** [comment]
Sure...

**Comment by jonpugh** [comment]
Ok, after re-writing I realize what I think I'm looking for is a "Best Practices" guide for organizations who want to start taking action and don't know where to start.

Does that make sense?

**Comment by sugaroverflow** [comment]
While you're thinking about how to tighten this scope and what you'd like from contributions, I came across this and it reminded me of your issue: https://gds.blog.gov.uk/2017/06/21/breaking-in-a-new-generation-of-public-speakers/

**Comment by sugaroverflow** [comment]
@jonpugh I think that makes sense, but it still feels a little broad. When you mean organizations, do you mean workplaces? Best practices for diversity and inclusion for employees?

I think if you could narrow it down a little more - it would make a great blog post that we could share :)

**Comment by sugaroverflow** [comment]
@jonpugh I'm closing this issue for now because I haven't heard from you in a while. It has the makings of a good idea - but I think it needs some narrowing of scope. If you come up with something, please feel free to reopen this issue _or_ add your topic to our meeting agenda for discussions during the meeting. 

Thank you!
