### ISSUE TITLE
Agenda for June 29 Meeting

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#103]
- document review
- new moderation guidelines
-  next action item
- Q&A CTA

**Comment by drnikko** [comment]
- attendance and demographic data gathering for all old drupalcons for a permanent page on drupal.org - checkin with @gdemet for data update

**Comment by ertiepie** [comment]
Link gathering: articles, etc. shared in Slack, for reference and sharing [limited Slack history.]

**Comment by drnikko** [comment]
A discussion of specific things we can do to make BDSM folks feel welcome.
