### ISSUE TITLE
Slack history export + viewer

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#104]
We have a way to get our channel (and any other public channel) history to json, but it's not human-friendly.  It would be great if we could take the json exported from slack, convert it to html and plop it onto github pages (or similar) for public consumption and easy reference. 

Locally `slack-history-export` seems to do a great job, so it would be trivial to put that on cron, have it add the file to a github repo.  Would be great if, in that same cron run, we could run a conversion script that does makes the json consumable by humans and then push that up.

**Comment by sugaroverflow** [comment]
Assigning to self to get my thoughts/background info on here and then I'll pass it to the tech team :)

**Comment by AlannaBurke** [comment]
Question: does this bring up any concerns with regards to making a safe space, etc? Are we creating this solely as an archive? Who will have access? What will we state is its purpose? How will we protect this from screenshots, etc? Will it be subject to our guidelines? Just want to make sure we are not putting things out there that will make people feel more vulnerable and less willing to interact.

**Comment by drnikko** [comment]
Those are great questions.  I think this came up primarily as a way for us to gather all of the links that are shared, not the transcripts of the conversations necessarily.   Though, we do everything in the open, I don't know that we're pushing to have 100% of the transcripts online.

**Comment by cleverington** [comment]
In response to Alanna's thoughts, I would support doing the exports for meetings, but I agree with her concern about maintaining a safe space for all Participants when they are not actively participating.

On the actual `slack-history-export`, let's touch base on it during tomorrow's meeting.

**Comment by alisonjo315** [comment]
> I think this came up primarily as a way for us to gather all of the links that are shared, not the transcripts of the conversations necessarily.

Ohhhhh okay, that's not what I thought, I should've read here first I suppose :)  I think our convo on the slack thread was with the idea that it *would* be saving transcripts.

**Comment by alisonjo315** [comment]
Just putting it out there: What if Drupal.slack were upgraded to non-free...?

Still would be great to scrape out and save all the link-shares, but, then at least there'd be a forever-archive.  I know it's money, but I think maybe it'd be worth it!

UPDATE: okay I thought it might be expensive but didn't know it'd be like, $10k/month expensive for the existing userbase... holy crap!!!!!!!!

**Comment by justAChris** [comment]
One though if we do make these transcripts publicly available is to anonymize who said what. The downside to this is people can still take what is said out of context. However, it looks like the most common use of inappropriate reposting of slack conversations include something like "A prominent Drupal leader said..."

**Comment by laughnan** [comment]
⚠️ Moving this thread to https://www.drupal.org/project/diversity/issues/2929245

**Comment by drnikko** [comment]
Thanks!
