### ISSUE TITLE
Create recurring calendar invites for team meetings

### ISSUE THREAD

**Issue by justafish** [drupaldiversity/administration#105]
Is there a google calendar for the group that we could put these all on to?

**Comment by cleverington** [comment]
Google Calendar can  be seen here: https://drupaldiversity.github.io/get-involved/ 

Missing Meetings
- Book Club
~- Content Team~ already there. 
- Technical Team
- Moderation Team
- Design Team

**Comment by sugaroverflow** [comment]
The content team meeting is on that calendar already. I updated your comment.

**Comment by sugaroverflow** [comment]
@cleverington @AlannaBurke @Cottser @sparklingrobots could you please post your meeting times in this issue and I will add them to the DD&( calendar?

I know some of them, but it makes it easier if it's here for me to do at once. Thank you! :)

**Comment by sugaroverflow** [comment]
Putting this on hold for a bit because there will not be team updates in this week's meeting - and we are discussing how to get more hands on deck / how to handle team meetings.
