### ISSUE TITLE
Create a Welcome Message to post in the DD&I slack on schedule. 

### ISSUE THREAD

**Issue by AlannaBurke** [drupaldiversity/administration#107]
This may be for both the content and technical team.
It would be great to have a slackbot response (or even automated!) to greet new folks in the channel with some info we pull together, including the guidelines. Can we spin up something quickly and then iterate on it?

**Comment by sugaroverflow** [comment]
Technically, the only thing we can do is slackbot responses. I think this will be very useful, but are there any concerns that people might feel uncomfortable if they join the channel - and slackbot gives them links or an intro?

**Comment by sugaroverflow** [comment]
Instead, I think it might be a better idea to compose a boilerplate text message with links that people can use to welcome newcomers to the channel. Such as: 

```
hey @newperson, welcome to DD&I. We are (short mission statement). 
links to guidelines, intro to DD&I, getting involved, and issues. 
```

**Comment by sugaroverflow** [comment]
Discussed this with the rest of the leadership team today :)

We agree that it might impersonal to have a slackbot response to every newcomer in the channel. Also, some people might just be lurking or checking it out and may feel ambushed by a set of links or an introduction. In order to achieve this we can have a scheduled welcome message every 24 hours or every 48 hours something like:

```
"Hello, welcome to the DD&I channel. We are [x], read more about this channel [x], and our guidelines are here [x]."
```

**Comment by sugaroverflow** [comment]
Next steps: 

- I'll work on writing the copy for this brief message. 
- @cleverington can you look into how we can set this up as a recurring post in the channel? Should we use reminders? Thanks!

**Comment by cleverington** [comment]
I would definitely go with reminders if you aren't going the route of direct-contact (which I think is a very positive idea).

Here's some examples:  https://get.slack.help/hc/en-us/articles/208423427-Set-a-reminder 

So something like this:

```

/remind #diversity-inclusion every other day "Hello, welcome to the DD&I channel. We are [x], read more about this channel [x], and our guidelines are here [x]."

```

Every other day is not *explicitly* listed as an option, but it should work.  Worse case scenario, we can instead set it to run once a week.

**Comment by sugaroverflow** [comment]
@cleverington Thanks! I'll work on the copy and I can set the reminder now that you've given me enough info :)

**Comment by sugaroverflow** [comment]
Here's a working copy for this :) I'll bring it up in the leadership meeting tomorrow and we'll see if we can get this run once a week or biweekly. 

Welcome to #diversity-inclusion, a channel for the Drupal Diversity and Inclusion Workgroup, also known as 'DD&I'. We are an independent collective of volunteers who advocate for greater diversity in the community and more inclusive events, help create safe spaces, and build the capacity of allies. Learn more [about us](https://drupaldiversity.github.io/about/), read more [about this channel](https://github.com/drupaldiversity/administration/blob/master/working-docs/slack-channel-introduction.md), and check out our [participation guidelines](https://github.com/drupaldiversity/administration/wiki/Drupal-Diversity-&-Inclusion-Participation-&-Moderation-Guidelines#participation-guidelines).

**Comment by rubyji** [comment]
I'd like to propose that this be combined with the participation guidelines bot. It doesn't need to be every day, but it could be. I'd also like to change the bot's schedule to post at a different time of day that won't collide with as many of our meetings. Maybe noonPT/3pmET?

Also, the autopost should include the time and day of our weekly meetings.

**Comment by AlannaBurke** [comment]
I don't think we should make the auto posts too big - people will ignore it. I'd rather have a few sprinkled throughout the day. I'm also happy to change the time of that one, noon just seemed like a good time! 

I think the welcome one could be a few times a week, same with the meetings one. i think the participation one should still be every day (maybe some day we can feel better about that ...)

**Comment by sugaroverflow** [comment]
Since I was supposed to get this going, I migrated this issue over to d.o as per #145 and assigned it to me! You're all credited, thank you!

https://www.drupal.org/project/diversity/issues/2924200
