### ISSUE TITLE
Please update channel intro with Guidelines

### ISSUE THREAD

**Issue by AlannaBurke** [drupaldiversity/administration#108]
https://github.com/drupaldiversity/administration/blob/4ef17a61d7aa853a1c0b7a693f89f6c848b35e79/working-docs/slack-channel-introduction.md - should be updated with the Guidelines and some nice text about following them please.

Guidlines can be found here: http://bit.ly/ddiguidelines
or in the wiki

**Comment by sugaroverflow** [comment]
The PR is up for this #116 for review.

**Comment by sugaroverflow** [comment]
Done, thanks @AlannaBurke !
