### ISSUE TITLE
DrupalCon Demographics

### ISSUE THREAD

**Issue by gdemet** [drupaldiversity/administration#110]
I've started a document with some historical data on DrupalCon demographics, focusing specifically on gender:

https://docs.google.com/document/d/1M_-aKhUY5kDVNNstplk16-8wJdkMf2KWFDPDjDY8yIU/edit

This document is available for anyone to view or comment on, and I will be adding additional data to it as it becomes available. The goal is add this data to https://www.drupal.org/association/drupalcon/locations as an accessible resource for our entire community.

**Comment by sugaroverflow** [comment]
Updating this issue with the task :) @gdemet needs some volunteers to help us go through past closing session videos and pull the data that was reported there.

The videos should all be here: https://www.youtube.com/user/DrupalAssociation

And then the information should be recorded in the Google Doc: https://docs.google.com/document/d/1M_-aKhUY5kDVNNstplk16-8wJdkMf2KWFDPDjDY8yIU/edit

**Comment by gdemet** [comment]
Thanks! Following last week's meeting, I should have all the volunteers I need for now, but will update if that changes.

**Comment by sugaroverflow** [comment]
Great! Thank you for letting me know :)

**Comment by sugaroverflow** [comment]
@gdemet we are in the process of moving DD&I to drupal.org #145.

Is the work on collecting demographics complete? If not, could you migrate this issue to https://www.drupal.org/project/issues? There are some existing issues to look at for examples.

**Comment by gdemet** [comment]
This is still a work-in-progress; I'll migrate over to a new issue on d.o

**Comment by gdemet** [comment]
This has now been moved to: https://www.drupal.org/project/diversity/issues/2924205
