### ISSUE TITLE
kink-friendly educational resources

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#111]
Documenting the results of a thread asking for resources for folks to read if they wanted to learn more about kink/BDSM.

**Comment by drnikko** [comment]
From Preston
- I began consulting friends I respect in the community to get a good cross-section of all the constituent groups, and I'll be sharing what they offer up here. First up is _When Someone You Love Is Kinky_ by Dossie Easton

- The YouTube channel Watts the Safeword (which I was also featured on incidentally) is also a good resource, especially for those interested in the gay kink community (edited

**Comment by sparklingrobots** [comment]
Moving to d.o.

**Comment by sparklingrobots** [comment]
Moved to https://www.drupal.org/project/diversity/issues/2929254

Tagging @drnikki !

**Comment by drnikko** [comment]
@sparklingrobots thanks!! <3
