### ISSUE TITLE
GitHub vs GitLab | Pros & Cons

### ISSUE THREAD

**Issue by cleverington** [drupaldiversity/administration#113]
The recent Coraline + GitHub post has left some uncertainty on the inclusivity of GitHub as an Organization and whether it would be best to continue with GitHub for the DD&I Group.  ( http://where.coraline.codes/blog/my-year-at-github/ )

This issue it for gathering Pros & Cons between the two Orgs, such as:
- Code of Conduct
- Actually actions taken for Code of Conduct violations
- Company actions and reactions
- Treatment of Employees, Diversity of Employees, and Diversity of Culture
- Technical Tools, such as: Issue Tracker, GitLab Pages vs GitHub Pages, GitHub Projects vs ????, etc.

Once gathered, will submit back to the team during a Team Meeting with the option already on the table _after_ we can see GitHub's response to Coraline's post.

Taking action will *not* be an easy endeavor, even if we could quickly migrate from GitHub to GitLab as the greater world already knows where we are. The Content Team would need some time to plan some announcements and press releases, the Technical Team would need to prep the move from GitHub Pages to Pantheon (or possibly GitLab Pages, depending on their offerings), the Leadership Team would need to make the final decision, and the Moderation Team would need to be prepared for knee-jerk negative responses.

So......

*Information gathering task only!!!!  =>^-^<=*

>  "We have the right to ask them to do better."
> ~~ @AlannaBurke

**Comment by sugaroverflow** [comment]
Closing this because we are moving to Drupal.org. Thank you for your thoughts! :)
