### ISSUE TITLE
Top 3 logo cleanup

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#12]
The top three logos are up for revisions/tweaks.  All three tied with 16 votes each.

The logos are: 

2 - ![19](https://cloud.githubusercontent.com/assets/254939/21432615/307f999e-c821-11e6-847d-2c7be52392d4.png)

4 - ![18](https://cloud.githubusercontent.com/assets/254939/21432617/34caee86-c821-11e6-9ff9-73b4e64a491f.png)

6 - ![17](https://cloud.githubusercontent.com/assets/254939/21432619/3733afc8-c821-11e6-9473-bb37f61dc7d6.png)

The unstructured feedback was:

- Drupal8 logo with the equal sign instead of the 8
- and number TWO but then the D8 logoformat with the equalsign
- For number 6 I would try some different colours. The grey in particular could be replaced or made less prominent.
- #2 I feel like the heart is a little too elongated and the drop should be bigger and more centered within it
- Six is wonderful but some of the colors could be brighter?
- Four is a strong mark that will hold up in small sizes, but it might be nice to add some color.
- less emphasis on the equal sign

**Comment by rubyji** [comment]
I can help with this if needed.

**Comment by star-szr** [comment]
I can help too, we should be ending up with vector assets I'd say - maybe an SVG?

**Comment by cleverington** [comment]
Once tweaked, I think the other two should still be maintained as.... 'branded' @drupaldiversity items, for re-use when just the logo alone might be boring.  (PowerPoints, Webpages, etc.)

All three look awesome and I known they'll look even better after tweaks.

**Comment by star-szr** [comment]
[drupaldiversity-logo2-v1.svg.txt](https://github.com/drupaldiversity/administration/files/669536/drupaldiversity-logo2-v1.svg.txt)

I can't attach an SVG directly, so here's a TXT that needs to be renamed to just 
end with .svg. This is logo 2 with no tweaks. At the very least, the vector paths need some love.

I can try to implement this suggested change:

> I feel like the heart is a little too elongated and the drop should be bigger and more centered within it

**Comment by rubyji** [comment]
I'm not sure I agree with having multiple unrelated logos. It's important
to be consistent, although we might use variants for different situations
of course.

--
Ruby Sinreich
lotusmedia.org
twitter.com/ruby

**Comment by cleverington** [comment]
@rubyji Right. Not logos, but just 'extra' items. Big logo in the center, smaller two off to the corners.

Sort of how GitHub's logo is the OctoCat, but there are variants of said Cat everywhere.  Just extra 'branding' materials, but not the official logo of DrupalDiversity.

**Comment by peacog** [comment]
Here's logo 6. I'm uploading a Gimp xcf first, renamed with a .txt suffix as @Cottser has done.
[drupal-diversity-logo-6.xcf.txt](https://github.com/drupaldiversity/administration/files/678605/drupal-diversity-logo-6.xcf.txt)
I don't know how to export as SVG. when I figure it out I'll post here.

**Comment by peacog** [comment]
And here's the SVG. Happy New Year everyone!
[drupal-diversity-logo-6.svg.txt](https://github.com/drupaldiversity/administration/files/678786/drupal-diversity-logo-6.svg.txt)

**Comment by drnikko** [comment]
#2 wins after a conversation in slack on 1/19/2017.  @Cottser will make tweaks to it in a new issue.
