### ISSUE TITLE
Agenda for August 10 meeting

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#120]
Please comment if you'd like to add something to the agenda!

**Comment by AlannaBurke** [comment]
Discuss #121 and get folks interested, think about boiling down into a concrete project.

**Comment by sugaroverflow** [comment]
Reminder for self to ask Govcon Organizers for a followup on how their D&I BOF went!

**Comment by dmkelner** [comment]
Yes, @sugaroverflow. Results of our first D&I BoF at GovCon.

**Comment by sugaroverflow** [comment]
+ demographics followup - d.o profile data to support demographics count

**Comment by sugaroverflow** [comment]
pinging @sparklingrobots for book club announcements ?

**Comment by sparklingrobots** [comment]
Pending thoughts from the rest of book club, here's what I think we're likely to say: 

We are continuing to read Twitter & Tear Gas for DD & I Book Club. Next week we will read Chapters 2 & 3.  It's available as a PDF here: https://www.twitterandteargas.org/downloads/twitter-and-tear-gas-by-zeynep-tufekci.pdf.

**Comment by rainbreaw** [comment]
DrupalCampLA went well. The screencast for the Fostering Diversity panel recorded successfully and can be found here: http://replay.uci.edu/clients/drupal/Fostering_Diversity_in_the_Professional_Drupal_Com_-_20170805_142642_11.html

The screencast for the Work-family balance panel, sadly, cut out at minute 20, before we really started discussing practical actions organizations could take and why those changes would benefit them. I recapped the key points in a comment on the session node here: http://2017.drupalcampla.com/sessions/finding-work-family-balance-drupal-professional and as soon as time allows I'll turn this into a blog post.
