### ISSUE TITLE
Resources for Diversity in Job Postings & Workforce

### ISSUE THREAD

**Issue by AlannaBurke** [drupaldiversity/administration#121]
Let's start gathering ideas, resources, thoughts, and feedback about providing resources to companies for promoting diversity in job postings as well as the workforce in general. If you're interested or have any ideas, please post here!

**Comment by RainbowArray** [comment]
I think this could be taken beyond job descriptions as well to the entire hiring process. The interview process, coding exercises vs take-home exercises vs paid trials and the impacts those have on diversity and inclusion efforts. As well as talking about networking and how to reach out to make sure there is a diverse applicant pool. Things to keep in mind when selecting applicants. Culture fit versus value add. Probably other bits too.

**Comment by angelamnr** [comment]
I did some digging for potential resources:

A quick run-down of the current tech job demographic landscape, and why the pipeline "problem" is a myth.
https://www.americanprogress.org/issues/race/reports/2017/03/29/429424/supply-diverse-workers-tech-silicon-valley-lacking-diversity/

A good write-up about the problems with culture fit.
https://resources.workable.com/blog/company-culture-fit

This site has a big list of resources for hiring more women in tech.
https://www.hiremorewomenintech.com/

This article outlines some common problems in job postings.
https://medium.com/@fox/your-tech-job-posting-is-broken-heres-how-to-fix-it-6db06b9769cb

 This article gives tips on creating processes for more inclusive recruiting. Has helpful resources at the end.
https://medium.com/@s_m_i/lessons-in-inclusive-hiring-what-ive-learnt-d8501d8925d5

**Comment by lkopacz** [comment]
This is a really good "Application Decoder" for inclusive language: http://gender-decoder.katmatfield.com/

**Comment by AlannaBurke** [comment]
Potential survey questions (for ideas, not phrasing!):
### Interviewing
- Have you ever refrained from applying to a job because of the language of the posting? Why? What kind of language in a job posting bothers you?
- How likely are you to apply to a job posting that requires various technology you have limited/no experience with (in addition to tech you excel in, ie, a posting for a Drupal Developer, which describes you, but also half a dozen techs you have not used)
- Have you ever turned down a job or no longer been interested in a job after the behavior or language of someone during the hiring process? Why?
- Have you ever been turned off to a job because of the "culture" of a company? Why?
- Have you ever been turned off to a job because of the age/gender/racial/etc makeup of a company?
- How do you feel about coding challenges when interviewing?

### Managing a company
- Have you as a manager/company owner felt unequipped or lacked the resources to increase diversity within your company?

**Comment by drnikko** [comment]
Hi, going to close this for now.  PLEASE reopen when we can get some traction and human energy behind it.

**Comment by AlannaBurke** [comment]
I'm addicted to Ask A Manager so every time i find a post related to diversity/inclusion i'm going to put it here! 

[1. Employee wants halal lunch options](http://www.askamanager.org/2015/11/employee-wants-halal-lunch-options-answering-would-you-rather-interview-questions-and-more.html)

[3. I used a white-sounding name on my resume and got way more interviews](http://www.askamanager.org/2017/02/i-used-a-white-sounding-name-our-meeting-food-keeps-getting-eaten-and-more.html)

[3.  Colleagues joke about “hard to pronounce” foreign names](http://www.askamanager.org/2017/10/my-coworker-is-making-me-late-my-boss-wont-answer-my-texts-and-more.html)

Just read an article this morning [#3 here](http://www.askamanager.org/2017/09/can-i-talk-to-my-boss-about-how-shes-treating-my-coworker-interview-exercises-and-more.html) that made me think about how employers should address religious holidays in the workplaces (and how they shouldn't)
