### ISSUE TITLE
PR#118 upgrade: change to "we"

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#123]
In the statement of beliefs, we should have a section that affirms that beliefs using "I" or we should replace the "we" with I to give more of a sense of ownership to community members.

**Comment by sugaroverflow** [comment]
Updated the PR #118 to add a section about "I". Made this decision because the document sounds better as "we" describing our values and then the participant affirming them. 

Closing this as it's resolved now. Hopefully this makes anons who were upset happy :)
