### ISSUE TITLE
Agenda for August 24

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#126]
@cedewey update on Safety Pin Box for Kids.

**Comment by sugaroverflow** [comment]
- possible community activist/other spotlight
- type of diversity series 01
- demographics followup + data-mining followup @gdemet and @davidhwang 
- followup on the resources and the survey being created for #121

**Comment by sugaroverflow** [comment]
assigned to @heyrocker because he's leading the meeting :)

**Comment by sugaroverflow** [comment]
Office hours are on 8/26 at 4PM PST.
