### ISSUE TITLE
Agenda for August 31

### ISSUE THREAD

**Issue by heyrocker** [drupaldiversity/administration#127]

**Comment by rubyji** [comment]
- Upcoming office hours. Ruby will do one next week. Nikki will do one the following.
- Spotlight?
- Reports from committees.
- Report from George et al?

**Comment by sugaroverflow** [comment]
skip the jobs #121 stuff this week.

**Comment by sugaroverflow** [comment]
do we have updates for demographics @gdemet?

**Comment by rubyji** [comment]
- Book club update?

**Comment by gdemet** [comment]
I'm out on vacation and don't have any updates, but @davidhwang might.

**Comment by sugaroverflow** [comment]
@rubyji book club updates stolen from the book club meeting outro
Next week we’ll finish off _Twitter and Tear Gas_. Please join us!

also no team reports, that's on hold for a bit. You can have an agenda issue for driving more participation if you'd like. There's also the option of a community spotlight (maybe not enough time) or a some-type-of-diversity highlight.

**Comment by sparklingrobots** [comment]
Yep, @sugaroverflow has it right. Same time as usual next week (9 am PDT on Wednesday).
