### ISSUE TITLE
Agenda for September 7 

### ISSUE THREAD

**Issue by sugaroverflow** [drupaldiversity/administration#128]
- upcoming office hours:: Ruby probably friday at 1PM EDT
- book club updates: Book Club will meet at 9 am PDT tomorrow to discuss the last of _Twitter and Tear Gas_
- Supplements to CoC idea/initiative: create an issue (@agentrickard)
- email survey blog posts (if I can get them done in time)
- should we get involved in g() discussion

**Comment by agentrickard** [comment]
See #129

**Comment by sparklingrobots** [comment]
Would it be possible to have a somewhat more in-depth convo about book club during this week's meetings?  Here are the questions I have:

- Even if you are not actively participating in book club at this time, we are very interested in your opinion so jump in!
- How is the timing of meetings? If we were to change the time, when would work best for you? 
- How is the pace of the reading for you? Do you like weekly meetings about a longer text? Prefer movie nights? 
- How is the format of the discussions? Do you like having pre-structured questions? Do you hate using Slack? 
- What would you like to see book club tackle next? 
- If you’d like to let us know your feelings in a more anonymous setting, here is a super simple one question anonymous survey: https://www.surveymonkey.com/r/X8CTZL3
