### ISSUE TITLE
CoC Resources Supplement

### ISSUE THREAD

**Issue by agentrickard** [drupaldiversity/administration#129]
We should consider adding additional resources to the CoC pages, readings, suggested trainings or seminars, and general approaches to help people navigate issues that arise.

Links to resources on CoC pages would be a good start. Inserts or program pages in printed conference materials would be nice, too, as would a consistent set of sessions that people could give (e.g. Intro to DD&I).

Some ideas for resources:

* Intervention and support resources (e.g. What do do if you see X.)
* Calling In / Calling Out -- http://everydayfeminism.com/2015/01/guide-to-calling-in/ guides
* Mediating your own response (some emotional intelligence work) 
* Conflict resolution resources

**Comment by sugaroverflow** [comment]
Resources that we'll need: (from the DD&I meeting today) @agentrickard 

- quick summaries of longer reading resources
- training workshops that are not Drupal-run
- DD&I presentation materials

**Comment by agentrickard** [comment]
I think the https://drupaldiversity.github.io/resources/ page is a good start. I want to look into repurposing some of that into a digest format.

**Comment by agentrickard** [comment]
See also https://github.com/drupaldiversity/administration/issues/134 and https://github.com/drupaldiversity/administration/issues/83

**Comment by sugaroverflow** [comment]
@agentrickard since we're moving to d.o (#145), would you like to migrate this issue to https://www.drupal.org/project/diversity/issues/? 

It can be related to https://www.drupal.org/project/diversity/issues/2923860. Thank you!!

**Comment by agentrickard** [comment]
https://www.drupal.org/project/diversity/issues/2923896
