### ISSUE TITLE
Contributor Code of Conduct

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#13]
Can we get behind using http://contributor-covenant.org/ or would we like to modify/enhance it for our purposes?

**Comment by rubyji** [comment]
I agree with their language. And I like the consistency of adopting a standard CoC instead of reinventing the wheel.

**Comment by bradleyfields** [comment]
After first read, I'd want to stay away from language like "...with dramatically low participation." Because it's not _false_, but it's too easily read as putting the blame on our choice, rather than on whether participation even feels possible.

**Comment by bradleyfields** [comment]
(Fwiw, submitted a PR for them to change that line.)

But otherwise agree re: adopting it as a shared standard. If we have modifications, we can suggest them to the community that uses the CoC before committing to forking something for ourselves.

**Comment by star-szr** [comment]
If I'm not mistaken, the wording we're considering adopting is http://contributor-covenant.org/version/1/4/, so it doesn't talk about "dramatically low participation". Sorry if I'm telling you something you already know @bradleyfields :)

I think we should adopt this CoC, and consider supplementing it as well since this is not a typical open source project. But I think putting this into place as soon as possible would be great.

> This Code of Conduct applies both within project spaces and in public spaces
when an individual is representing the project or its community. Examples of
representing a project or community include using an official project e-mail
address, posting via an official social media account, or acting as an appointed
representative at an online or offline event. Representation of a project may be
further defined and clarified by project maintainers.

This clause seems like it would allow people to (for example) publicly tweet horrible things as long as it's from their personal account. If people agree that this type of scenario would be unacceptable for this group, maybe we can at least further define "Representation of a project" for our case.

**Comment by bradleyfields** [comment]
Oh, sorry. Realize now it wasn't clear whether I was talking about the CoC itself or the text on http://contributor-covenant.org/ that introduces it.

Also agree that that clause could use some work. Though, I'd suggest that there shouldn't be a project representation requirement at all. (Maybe that's your point too, @Cottser.)

**Comment by drnikko** [comment]
@bradleyfields @Cottser It raises questions for me:
- what classifies participation (is it being here in the issues, is it being in the slack channel, etc..)
- and if an individual participant is tweeting things that are objectionable, what is our position?

It seems easier to establish some guidelines for this before a situation arises rather than in the midst of one.

**Comment by bradleyfields** [comment]
How about changing the start of the clause to this?
>This Code of Conduct applies both within project and public spaces. It applies when an individual is representing the project or its community....

And then adding something after that paragraph—something that speaks to conduct not done as representation of the community or project. E.g., someone, via their personal social account, could publicly behave in a way that violates the CoC's spirit. It'd start something like:
>However, this Code of Conduct can also apply to behavior that does not appear to represent the project or community. Examples of such behavior include targeted harassment, threatening violence or physical harm....

Could borrow from Twitter's reporting mechanism for examples.

**Comment by drnikko** [comment]
I agree that this covenant isn't perfect as is.  I also would like to adopt something sooner rather than later.

https://drupaldiversity.github.io/get-involved/ endorses the 1/4 version as our CoC.  I'm marking this as closed only because we have a CoC now, but I don't think the conversation has to end on tweaking it or adding to it as our needs change and as situations inevitably arise.  

I'm also not sure *quite* where this stuff should live, so perhaps when the time comes to revive this, we can do it as a PR on the website.  

Thanks @bradleyfields @Cottser @rubyji for weighing in on this.

**Comment by drnikko** [comment]
Reopening this for comment in light of recent issues...

**Comment by Badfaerie** [comment]
Opensource.com has a great article on tips for increasing diversity in open source projects.  The article recommends the Contributors Covenant. There are a lot of really good reasons to use it and not a lot of down sides. I think that this document would have covered the recent kerfuffle.

Understand, you can always extend this document with project specific amendments. In addition to the Contributor's Covenant, you are expected to....

https://opensource.com/life/16/3/creating-welcoming-and-inclusive-open-source-space

**Comment by damienmckenna** [comment]
I've added PRs against each project to add a CODE_OF_CONDUCT.txt file that just copies the text from the existing drupaldiversity site.

* https://github.com/drupaldiversity/administration/pull/47
* https://github.com/drupaldiversity/diversity-of-the-web/pull/75
* https://github.com/drupaldiversity/drupaldiversity.github.io/pull/15
* https://github.com/drupaldiversity/event-organizer-packet/pull/31

**Comment by sugaroverflow** [comment]
Since a code of conduct has been added to each repo - thank you @damienmckenna - can we close this issue for now @drnikki ?
