### ISSUE TITLE
Agenda for Sept 14

### ISSUE THREAD

**Issue by sugaroverflow** [drupaldiversity/administration#130]
- upcoming office hours
- book club updates
- Supplements to CoC idea/initiative #129 
- possibly jobs resources #121 
- demographics list update
- should we get involved in g discussion (depends on leadership meeting)

**Comment by sugaroverflow** [comment]
are there upcoming camps we should pitch a DD&I BOF or discussion at?

**Comment by sugaroverflow** [comment]
possible DC Vienna discussion agenda item. Are there people going? How do they feel about it and how we can help? Maybe we should have a BOF?

**Comment by sugaroverflow** [comment]
+ #131 twitter mentors in the community idea - possibly a discussion

**Comment by rubyji** [comment]
- Possible discussion of governance issues, and meta discussion of whether we should discuss it.

**Comment by rubyji** [comment]
@drnikki Do you have a time we can promote for your next office hours?
@sparklingrobots Will you have a book club update?
@davidhwang Are there any updates on the DrupalCon demographics analysis?

**Comment by sugaroverflow** [comment]
@rubyji lets minus the twitter mentors from the agenda till we've discussed initiatives next week.

**Comment by rubyji** [comment]
It might also be good to have a discussion of Dries' recent blog post about contributing, but I don't know bc I haven't read it yet.

**Comment by sparklingrobots** [comment]
@rubyji Book club does have an announcement:  

Next week (Wednesday, September 20) at 3 pm PST we will be discussing @ok_lyndsey's talk "Resisting Algorithms of Mass Destruction".  If you'd like to join, please watch her talk in advance: https://www.youtube.com/watch?v=g5H5_sPrbBc and let me know if you have any questions!
