### ISSUE TITLE
Resources: Encoding values & biases into software

### ISSUE THREAD

**Issue by rubyji** [drupaldiversity/administration#134]
I have been thinking a lot about how we encode our values and inherent biases into the software and tools we create. I would like to eventually make a blog post and a presentation about this. I've been compiling links for a while, and have gotten some good suggestions from the DD&I Slack channel. 

I realized I should be sharing these here so people can see them and to make it easier to add links to the list. 

Here is what I have so far, please feel free to add to it!

https://motherboard.vice.com/en_us/article/code-is-political
https://www.theguardian.com/technology/2017/apr/13/ai-programs-exhibit-racist-and-sexist-biases-research-reveals
https://en.wikipedia.org/wiki/Critical_code_studies
https://www.hastac.org/initiatives/hastac-scholars/scholars-forums/critical-code-studies
https://jacquesmattheij.com/no-politics-please-we-are-hackers-busy-improving-the-world
https://www.propublica.org/article/facebook-hate-speech-censorship-internal-documents-algorithms
https://www.technologyreview.com/s/608248/biased-algorithms-are-everywhere-and-no-one-seems-to-care/
http://bridgetkromhout.com/blog/2017/06/04/in-the-kingdom-of-the-blind/
https://www.wired.com/story/machines-taught-by-photos-learn-a-sexist-view-of-women

**Comment by drnikko** [comment]
Tagging myself to get these up on the website for non github folks to find it.

**Comment by rubyji** [comment]
I'll be working on adding these links to our resources page. Follow along at https://www.drupal.org/project/diversity/issues/2924467/
