### ISSUE TITLE
Sketch out a long-term mentorship or limited term contribution accelerator program. 

### ISSUE THREAD

**Issue by sparklingrobots** [drupaldiversity/administration#135]
Based on concerns raised re: Dries' blog post on contribution demographics, we had a few ideas in the channel:

- [idea] . Re: code contribution. I know that some of us know/are contributors to the project, whether core or contrib.  And I know many of us are interested in contributing despite fears that we aren’t welcome/not knowing how to join. Could we pair established maintainers/contributors with mentees?
- [idea] Totally off the rails here, but could we (not we as DD&I but we as Drupal community) have a seasonal "accelerator" group or something? Group of people that get paired with established maintainers or contributors to learn/grow. And then we can cycle the group?

@rachel_norfolk (not on github? diff username?) said that some of this work is already happening in Drupal Mentoring, which I had no idea about.  Let's use this issue to find out what's already happening and sketch out some next steps for a program like this!

**Comment by sparklingrobots** [comment]
Tagging @rachellawson @sugaroverflow @alisonjo2786 @agentrickard

**Comment by alisonjo315** [comment]
Also..... I wonder about connecting ppl who are participating in issue threads with self-identified "Mentors" on the spot.  idk if this should be part of the same task, or if it's too different, so, just saying it "out loud" for now.

**Comment by sparklingrobots** [comment]
Sounds like this work is happening on an ad hoc basis right now (per @rachellawson in the channel).  

Things I'd like to consider: 
- Who could be a mentor?
- Who could be a mentee?
- What term-length would be useful? 
- How do we get a light-weight version of this off the ground to verify if it is useful?

**Comment by sugaroverflow** [comment]
- who will run this

If it's a community based operation, I don't know if it'll get the same attention and impact as what we'd hope for it. 

It's also something that _might_ be out of scope for DD&I to manage - but is an idea we could promote as a recommendation (though the others on leadership may have different thoughts).

**Comment by alisonjo315** [comment]
- stated goal of this effort

**Comment by sparklingrobots** [comment]
- what are we asking of both mentors and mentees
- how do we judge success of the effort

**Comment by alisonjo315** [comment]
Sharing a message from a DD&I member on slack earlier this afternoon (with their permission), that I found inspiring wrt mentorship needs/potential -- i.e. direct impact that mentorship could have on mentees, AND indirect impact of (1) more individuals making code contributions (2) greater diversity of code contributors, ergo more "role models who look like me" etc etc:

> One of the biggest barriers that I feel personally is that I’m not sure if my opinions and contributions to the community are valued as much as people who are in the club, like on top contributor lists, because not only is that group quite homogenous, but I never hear them indicating that they have any problem with that status quo. I assume I will be perceived as disruptive by my very presence.
> So as embarrassing as it is, I think Dries and other leaders need to make some very baby steps just to show that they do welcome people with different backgrounds *and ideas* from theirs. It will be a while before I am convinced of that.

**Comment by alisonjo315** [comment]
(possible goals, without digging into measurement *yet* :) )
- more code contributors
- greater diversity of code contributors

**Comment by sparklingrobots** [comment]
Benefits to a project like this (related to stated goals, maybe not exactly the same)
- It’s one thing to get mentored/mentor at a sprint, but a long-term, one-on-one relationship would be a HUGE step-up for someone looking to get into contribution
- it gives established folks a direct way to make an impact on D&I goals, which I think has a lot of positive impact on its own (e.g. you move from feeling bad about it to knowing you are helping)

**Comment by sugaroverflow** [comment]
Benefit to community: 
- Grows the overall contribution pool because we're easing people into it and giving them more of a chance to learn and grow. 

I know some people struggle with contributing even though they were mentored at a Drupalcon or camp because it all happened so fast and they weren't able to feel comfortable enough.

**Comment by sparklingrobots** [comment]
@sugaroverflow totally agree. And it's easy to feel burned out post DrupalCon.   Also, not everyone has access to DrupalCon and mentored sprints in the first place.

**Comment by sparklingrobots** [comment]
Just as an fyi to everyone here: I cross-posted a little blurb about this in the #mentoring channel just to let them know about what we're up to.  @ekl1773 also expressed some interest in this concept and is also involved in core mentoring.

**Comment by rachellawson** [comment]
I might have to spell this out but you do realise that mentoring already takes place not just in code contribution but even here in the DD&I group? Plenty of you have stepped into contribution here and been guided by @drnikki and others. You have grown into those roles and are now doing good things. 
Mentoring is taking place here, now, in front of you. You are already part of it.

**Comment by sparklingrobots** [comment]
@rachellawson Not enough +1s in the world for that reminder!  <3 <3 <3

**Comment by gapple** [comment]
A lot of module maintainers are probably in the position of only being able to minimally maintain or improve their module with their available time; what's needed to help them be active and regular mentors in that time instead?

Are there things from the Google Summer of Code program that could be re-used to create an ongoing mentorship / accelerator program?

**Comment by agentrickard** [comment]
@gapple the challenge there is getting maintainers to think like Project or Product Managers. Views and Panels went through this transition successfully. If we can provide some templates or models for how people might manage such things, that might help.

The key is writing feature criteria and then coaching people through how to do it. Here's a sample, perhaps. https://github.com/agentrickard/domain/issues/159

**Comment by rachellawson** [comment]
There are movements to try and bring Gabor's excellent Rocketship tool and a whole bunch pf PMs into the equation. Make it available as a resource for more maintainers and initiative leaders. I think Sharon Vettes wants to sprint on this at Vienna.

**Comment by agentrickard** [comment]
FYI -- https://www.drupal.org/project/rocketship powers http://drupal8multilingual.org/

**Comment by rachellawson** [comment]
I just want to record in here some of the excellent ideas made on Slack. Hope that's okay.

```
Ruby Sinreich
[22 hours ago] 
:four:.1 @rachel_norfolk would like to talk about what actions we can take as part of mentoring in Drupal that would help with D&I.


Rachel Lawson
[22 hours ago] 
Yes, so are there any actions that we can build into what we do at things like mentored sprint days that help encourage a more diverse list of attendees (& mentors!)


Ruby Sinreich
[22 hours ago] 
I’ve only attended one sprint and had no idea what I was doing, so I’m not entirely sure. I know there’s already a lot of mentoring, but I still felt *extremely* impostor-y there as a woman and not a big coder.


Ruby Sinreich
[22 hours ago] 
Maybe meeting mentors and other sprinters in advance? Like possibly a reception for people who are curious about contributing?



Fatima Khalid [22 hours ago] 
I think the first time sprinters workshop is really useful, but the core mentoring room was intimidating for me the first time too.


Tara King
[22 hours ago] 
One thing that helped me understand I could be a mentor was when an existing mentor roped me into a leadership role with a group of newbies who had just sliiiiightly less knowledge than i did



Fatima Khalid [22 hours ago] 
Oh, I like the idea of pairing people up! I got way more comfortable in the sprint room after talking to or hanging out with people outside of it.


Tara King
[22 hours ago] 
and then he pointed out I was already mentoring! Made it much easier the next year to sign up officially.



Rachel Lawson
[22 hours ago] 
I like the idea of a “meet the mentors” session!


Lyndsey Jackson [22 hours ago] 
Not sure if it's exactly in line but I've had 2 things on this this week. One is a chat in #nonprofits where someone is looking for help it made me wonder about a mentor/buddy system - part of this could be encouraging and supporting sprints etc.

I also found a cool remote job online and posted that if a woman had 60-80% of skills and still applied and got it I'd help find them a Drupal mentor so they felt confident about they 40-20 - one person DM'd me :hugging_face:


Fatima Khalid [22 hours ago] 
Totally with @sparklingrobots here!
When I was at MWDS, @yesct introduced me to someone looking to contribute who knew much less than I did and also sat us next to @tim.plunkett so I didn't feel like I was on my own in mentoring. He ended up driving a lot of it, but I think it was a good setup because I wasn't comfortable mentoring on my own.



Rachel Lawson
[22 hours ago] 
The reality is, *I* find it all a bit intimidating. Imposter Syndrome is strong in this one!



Tara King
[22 hours ago] 
Yep--having an experienced mentor who was my back-up really was great. I found the whole introduction process to official mentoring very welcoming, btw, and honestly still use some of what i learned there when combating imposter syndrome! (edited)


Ruby Sinreich
[22 hours ago] 
Yes, and even “meet the mentors” might be too much of an ask. I’d want it to be more like contrib-curious.


Rachel Lawson
[22 hours ago] 
You’ll notice that some of the mentors have coloured tape on their Tshirts - it’s so 1st time mentors know who has done it all before


Rachel Lawson
[22 hours ago] 
“Contrib-curious”. Yeah - I like the term



Rachel Lawson
[22 hours ago] 
So it sounds like there is definitely a thing we can do to make entry into the mentored sprint room more welcoming. We can work on that.



Rachel Lawson
[22 hours ago] 
For the record, I’m no hard core dev. I can write a bit of code here and there and fix a few issues but not proper dev. _And I’m A Mentored Sprint Lead in Vienna._



Rachel Lawson
[22 hours ago] 
But thanks for things above. Really helpful


Rachel Lawson
[22 hours ago] 
Actually, if any of those who have spoken above of the feelings around coming in to the sprint room are in Vienna, I couldn’t think of any better people to help greet people coming in and help make them comfortable. You would be perfect and you have already shown you have the right skills



Gus Austin [20 hours ago] 
Hi there - I'm part of a team responsible for bringing https://groups.drupal.org/drupal-dojo back after a five year hiatus. For those not around when it was previously active, the Dojo was incredibly successful as sort of a safe, friendly training ground for newcomers to Drupal and the community.

This time around we have access to better tools that will enable us to more effectively run and sustain the community run program.

I think much of what's suggested here could further expand Drupal Dojo as a warm, welcoming, inclusive community.

We also should be able use the Dojo as a forum to help carry out the mission of this group.



Geoff Appleby
[15 hours ago] 
Are there ways to match people up outside of sprints as well?

I have a new module that I would love to collaborate with someone new to contrib development on, but I don’t know how/where to reach out to people who may be interested. (https://twitter.com/gappleca/status/886010392882761729)

Alternately, if someone was interested in getting involved but doesn’t know where to start, I’d be happy to guide them on contributing to a module they’re more passionate about, and helping them get some issues through to RTBC on other projects.
Geoff @gappleca
Anyone want to collaborate on a Content-Security-Policy module for #Drupal 8?
Don't know how it would work?
Great! Neither do I!
TwitterJul 15th at 12:51 AM


Tara King
[14 hours ago] 
@gapple we were also talking about something like this later in the meeting. Nothing concrete yet but there's a GitHub issue around it... On mobile so gimme a minute to find the link


Tara King [14 hours ago] 
Ha--you already found it. :grin:
```

**Comment by gusaus** [comment]
Couple quick thoughts on how DD&I could interface with the [Drupal Dojo](https://groups.drupal.org/drupal-dojo) and related community mentoring groups

- create a Diversity & Inclusion group on http://drupaldojo.com/ -  
- use Drupal Dojo tools (Twitch.tv, #drupal-dojo Slack, websites, drupal projects/issue queues, etc)  to run coding sprints, online training sessions, podcasts, and more
- help Drupal Dojo and related events and projects be diverse and inclusive as possible

As a community run platform, members of this group could play a key role in helping use the Dojo to follow through with many of the next steps here - 
https://docs.google.com/document/d/1qNbZYRBuSVfxuyF9G6r3YTMcVFj9TCqoe3Bpegk5hKw/edit?usp=sharing 

Many of which are already shared goals and objectives.

**Comment by sparklingrobots** [comment]
I tried to sum up what we've talked about here in this [Google doc ](https://docs.google.com/document/d/1ib9c9IDxlEgdxiwOMAY04VF3HWXLAWgszaOHtt9Kw1c/edit?usp=sharing)(editable by anyone). 

I am copy/pasting the contents below so you all can see the work but let's keep working in the google doc. (Is there a better way to handle this? I'm newish to GitHub.)

I think we could come up with a basic plan of how this could happen, and then assess whether it *should* happen and who wants to be involved. How does that sound as a more defined goal for this thread?

---doc contents below---

**Stated Goal of this effort** 
To increase code-based contributions from individuals from under-represented groups to the Drupal project.

**Benefits to the Community**
Drupal will have more contributors.
Drupal will have more diverse contributors. 
Mentees will improve their skills and community connections.
Mentors will have more help with the work they maintain.

**Concerns**
Who will run this program? 
Are there existing groups we can connect with, such as DD&I, Mentoring, DrupalDojo, Google Summer of Code?  The Panels and Views teams? Sharon Vettes? Rocketship? 
How will we find mentors and mentees?
A lot of module maintainers are only able to minimally maintain or improve their module with their available time; what's needed to help them be active and regular mentors in that time instead?
Are there things from the Google Summer of Code program that could be re-used to create an ongoing mentorship / accelerator program?
How will we measure success? 
Can we get support from higher in the Drupalverse?

**Comment by sparklingrobots** [comment]
Update: There is a new #ddi-contrib-team channel in slack for any interested parties to discuss this project.

**Comment by sparklingrobots** [comment]
There's a new google doc for ideas about the theme folks are considering building: https://docs.google.com/document/d/12IsWjp8VYFlp5B4rUBg86_qEuZOjkhYkWTkEaTR_CRU/edit

**Comment by drnikko** [comment]
@sparklingrobots would you like a drupaldiversity repository to store your work in, or are you okay with the google doc?

**Comment by sparklingrobots** [comment]
@drnikki Thanks for the offer! For now we can stick with google docs but we'll talk about it in our meeting later this week and see if folks prefer something else.

**Comment by sparklingrobots** [comment]
@drnikki That said--if there is a way that it would be helpful for us to organize our work so as to not clutter up what everybody else is doing, let me know and I'll make it happen.

**Comment by sparklingrobots** [comment]
@drnikki Can we please have a drupaldiveristy repository after all? I think most of our project work will live on d.o but we need a home for the meta-info of organizing the mentoring program itself. Thank you!

**Comment by drnikko** [comment]
@sparklingrobots with pleasure  - https://github.com/drupaldiversity/contrib exists and you're an administrator and so can proceed as you wish.  Thank you for everything that you're doing with this.  It makes a big difference. <3 <3 <3

**Comment by sparklingrobots** [comment]
@drnikki Thank you thank you thank you!! I am happy to be doing it and the team that has coalesced here is amazing.

**Comment by sparklingrobots** [comment]
I'm going to go ahead and close this issue since we are getting rolling a) with our first groups and b) in our shiny new repo.
