### ISSUE TITLE
Agenda for Sept 21

### ISSUE THREAD

**Issue by sugaroverflow** [drupaldiversity/administration#136]
some possible agenda items: 

- upcoming office hours
- book club updates
- demographics updates
- something for DC Vienna
- actionable items to make drupal more diverse doc
- discussing initiatives

**Comment by sugaroverflow** [comment]
- call for volunteers to be interviewed via phone or chat about their DC Baltimore experience with DD&I

**Comment by drnikko** [comment]
speaking as an individual not as a DD&I person - announcement of safe non-male space for governance discussion as a direct attempt to get more people involved especially in CoC & CoC enforcement conversations

**Comment by heyrocker** [comment]
DrupalCon social. Tuesday night at 18:00, Das Campus. http://dascampus.at/

**Comment by drnikko** [comment]
Closing
