### ISSUE TITLE
Agenda for Sept 28

### ISSUE THREAD

**Issue by rubyji** [drupaldiversity/administration#137]
possible agenda items:

- upcoming office hours
- book club news
- demographics updates
- actionable items to make drupal more diverse doc
- updates on initiatives

What else?

**Comment by RainbowArray** [comment]
Putting together a small, diverse contribution team or teams.

Discussion questions:
- What would make such an effort diverse? How to keep people supported?
- Definite interest in working on a contrib theme, is there also interest in a team working on updating contrib to use new Media API and/or updating tests in core?
- Set up a regular meeting time?
- Anyone else interested in participating? Leadership roles?

Might be good to have this one the agenda the next couple meetings.

**Comment by sparklingrobots** [comment]
Book club news: Book club is changing to a new time and format. New time is noon EST on Fridays. First meeting at the new time will be next Friday (10/6--not tomorrow!) at noon EST. We'll be reading the first two parts of @vcastillo's _Why Most Conversations in Tech About Diversity Are Bullshit — and What to Do About It_ ([first part](https://uxdesign.cc/why-most-conversations-in-tech-about-diversity-are-bullshit-and-what-to-do-about-it-part-i-eca4962a3e7d), [second part](https://uxdesign.cc/part-ii-why-most-conversations-in-tech-about-diversity-are-bullshit-and-what-to-do-about-it-6fbe7b0fd6fc)).  

The new format is simple: No more prepped questions, just open discussion.

Ping @sparklingrobots if you want to be reminded in advance of these discussions.
