### ISSUE TITLE
Clean up Resources page or tell Ruby how

### ISSUE THREAD

**Issue by rubyji** [drupaldiversity/administration#138]
I put a lot of effort into creating this on a wiki page but now that it's on our website I don't know how to edit it. https://drupaldiversity.github.io/resources/

Some of the formatting is broken and the whole thing could be updated with the links at https://github.com/drupaldiversity/administration/issues/83 and https://github.com/drupaldiversity/administration/issues/134

**Comment by cleverington** [comment]
@rubyji If you provide it to me in a Google Doc, I can get the change made in a few minutes later this evening or tomorrow.

I'll leave the Issue open though until I can get a small work instruction created within the Wiki. There is a way to 'print to Markdown' with a special JavaScript file.

**Comment by rubyji** [comment]
Thanks, @cleverington! For now could you please fix the broken syntax there? (Links in bullets 4 & 9, and space between 3 & 4.)

I can easily edit a markdown document, I just don't know where it is or what the workflow is to publish it. I may not even be asking the right question.

**Comment by cleverington** [comment]
No worries.

And, as for editing, if you are familiar with the GitHub Editor, you can actually 'live edit' a page and then submit your changes as a P.R.

I'll look at those changes this evening.

**Comment by rubyji** [comment]
So I go here and just start editing? https://github.com/drupaldiversity/drupaldiversity.github.io/blob/master/resources.md

**Comment by cleverington** [comment]
Yep. Just click the little Pencil icon.

I'll ask (if your permissions are high enough) if you want to commit it to master.

If they _aren't_ high enough, it'll ask if you want to create a PR in a branch with your Username as the title of the branch. Either way, select that second option, that way we can review in a PR before approval.

**Comment by rubyji** [comment]
I did this. https://github.com/drupaldiversity/drupaldiversity.github.io/pull/39

**Comment by cleverington** [comment]
@rubyji Generally takes around 20 minutes for changes to 'populate' (at **absolute** longest) on the site. You'll generally see all changes within around 2 minutes.

Look for it. ;-)
