### ISSUE TITLE
Agenda for October 5 meeting

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#139]
- governance chats / governance & CoC issues
- plug for Open Demographics

**Comment by sparklingrobots** [comment]
Hope you don't mind some unsolicited additions! I might not be able to make the meeting so wanted to make sure to get these in.

- Book club is Friday (tomorrow) at noon PST. We'll discuss parts 1 & 2 of @vcastillo’s "Why Most Conversations in Tech About Diversity Are Bullshit — and What to Do About It".  New format is Bring Your Own Questions (BYOQ).  Part I: https://uxdesign.cc/why-most-conversations-in-tech-about-diversity-are-bullshit-and-what-to-do-about-it-part-i-eca4962a3e7d Part II: https://uxdesign.cc/part-ii-why-most-conversations-in-tech-about-diversity-are-bullshit-and-what-to-do-about-it-6fbe7b0fd6fc

- Mentoring team is meeting right after this in #ddi-contrib-team for the first time. During this meeting we'll formalize the first group/cohort of mentors/mentees and develop a plan to support them as they work together.

**Comment by sugaroverflow** [comment]
maybe share some of the resources in https://github.com/drupaldiversity/administration/issues/134?
