### ISSUE TITLE
Goals for DCBaltimore

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#14]
Can we formulate a list of measurable goals to work towards for DC Baltimore?  We need to let Amanda know if we have specific asks for the booth/table/conference space by the end of January.

Some examples might be:
- pass out 500 pieces of literature about the working group and it's goals
- have one meeting/day
- get 100 more people to join the slack channel 

We'll use these goals to determine the most effective actions we could take.  Some options include:
- having a formal booth/space on the conference floor
- having a quasi booth by taking over a lunch table
- getting space at someone else's booth
- running our own hallway track, etc etc.
- figuring out the best kind of swag to give out

from @rubyji 
I hope that in addition to a session we can host a BOF and recommend a hashtag for people to use on Twitter if they want to comment about diversity & inclusion at the event.

from @davidhwang 
- introducing the group to the major camp organizers: govcon, midcamp, txcamp, pnwds, etc.
- one meaningfully attended BoF session on tues/weds (thurs tends to be a recovery day for most)
- and a coffeebreak/lunchtime table-and-or-booth presence all three days (no attendance or paticipation goals there per se, just having it available)

from @heyrocker
focusing more on internal goals in the beginning (getting a booth staffed, successfully running a bof, having a lunch table staffed all three days) is great regardless of any external participation.

**Comment by davidhwang** [comment]
To more fully expand on my thoughts from Slack:

- Introductions with Major NA (and maybe even European?) Camp Organizers. Need not be formal or structured, just introductions and connections made. 

-- BADCamp (easily done, I'm one of them 👍, populist, hrodrig, annabella, etc. )
-- Design4Drupal (danigrrl, etc)
-- Drupal Government Conference (bendygirl, etc)
-- DrupalCamp FL (ultimike, etc)
-- Midcamp (zendoodles, kthull, etc)
-- NYC Camp (willykaram, etc)
-- TexasCamp (Steph El-Hajj, etc)
-- PNWDS (not sure who the team is this year... rootwork?)

- One highly publicized and well-attended (100 people?) BoF session, hopefully one that results in 
0. gathering a wide variety of folks who are interested in diversity topics and taking progressive action in our Drupal-centric communities
1. significant connections made, both horizontally across geographies but also up and down the structures of power in the Drupalverse (i.e. bosses and organizers and decision makers)
2. more than the surfacing of pain points -- yes, there are many things where we can do much better, but it should be more than an group airing of grievances. 
3. a minimum of trolling (drnikki, we're all looking at you to hold the gavel)
4. a network of peers that can stay in collaborative touch throughout the year, as we disperse to our local orgs

- Coffeebreak/Lunch drop-ins that can pique the attention of interested folks who might not be able or comfortable to come to a large group event. More 1:1 discussions and recruiting type stuff.

**Comment by sugaroverflow** [comment]
Would it be possible to have an anonymous suggestions/comments box? I imagine there would be people who don't feel as comfortable chatting up at the booth/quasi-booth table and can leave anonymous feedback.

**Comment by rubyji** [comment]
Here are some difficult to measure goals I have in mind:

- To increase people’s understanding of the pitfalls of working with homogenous groups. 
- To help people be more aware of their own culture and privilege as distinct and non-universal. 
- To dispel the myth that hiring people that don’t look like Mark Zuckerberg and Dries Buytaert means lowering standards.

**Comment by drnikko** [comment]
I'm going to close this since drupalcon is next week.  We will be working to gather some "what we accomplished" facts after the con is over.

**Comment by drnikko** [comment]
This is related to https://github.com/drupaldiversity/drupaldiversity.github.io/issues/18 as a review blog post.
