### ISSUE TITLE
Agenda for DDI Mentoring Initiative Meeting #1 (2017.10.05)

### ISSUE THREAD

**Issue by sparklingrobots** [drupaldiversity/administration#140]
1. Introductions (name/location/reason they joined us today)

1b. Meeting Overview: 
Goal of the project: To increase code-based contributions from individuals from under-represented groups to the Drupal project.

This channel right now is being used to organize a mentoring program. During this meeting I'd like to formalize the first group/cohort of mentors/mentees and develop a plan to support them as they work together.

2. Survey to find out: Names, Contact info, skills/connections you can offer, skills/connections you want to develop, what do you want to get out of participating in this project?

3. Form a team (or multiple teams) of 6-10 to work together for 2 months as the first cohort(s).
--Which project to tackle first? ok_lyndsey's accessible NFP theme idea? something else? 
--Who is taking the lead on the cohort's project? 

4. How will the cohort(s) work together?
--Priority is to use standard community tools & practices (e.g. drupal.org), but what will we use to supplement? Is this slack channel enough? DDI repos? Drupal Dojo group? 
--More stable place for documentation of our process/resources/meeting notes? 

5. When will we meet on an ongoing basis to support the mentoring program as a whole (as opposed to the specific work of a cohort)?

I don't think we will have time for these but they are on my mind: 
6. How will we measure diversity of the cohort(s)?

7. How will we measure success of the cohort(s)? 

8. If time remains, how do we want to work with other groups, like Drupal Dojo?

**Comment by RainbowArray** [comment]
I'd maybe just add another bullet point under number 3:
- If there's sufficient interest for a second cohort group that's more back-end based, maybe look at Media API updates in contrib? And/or working on updating tests in core?

**Comment by sparklingrobots** [comment]
Meeting notes: https://docs.google.com/document/d/1SmXnIwRWmmDfoRGBFB3KYPURIheZ3zhSh0npFEOiSZg/edit?usp=sharing
