### ISSUE TITLE
Agenda for Oct 12

### ISSUE THREAD

**Issue by rubyji** [drupaldiversity/administration#141]

**Comment by rubyji** [comment]
I'd like to discuss merging our our reading list (https://github.com/drupaldiversity/administration/issues/83) into our public resources page (https://drupaldiversity.github.io/resources/) and adding more organization. I am willing to take the lead on it unless any librarian wants to step up. Could possibly also incorporate some other resources like Encoding values (https://github.com/drupaldiversity/administration/issues/134) and  *maybe* Diversity 101.

**Comment by sugaroverflow** [comment]
Agenda (so far)

- Book Club Announcements
- consolidating our resources page. 
- feedback on how leadership should deal with people who make the community more hostile to marginalized people. 
- DD&I Contrib team invite/update
- Support for camp/con presentations
- Drupalcon Nashville DD&I + how to make it safer
- possibly governance? share Nikki's medium post

**Comment by rubyji** [comment]
I feel like the item about disparaging presentation has (rightly) morphed into an issue about how the DA should deal with people who make the community more hostile to marginalized people. For some this may be a question of the process of the CWG - how they respond, what enforcement they or can't do, whether it's public or private. Personally, I feel like the CWG is designed to deal with interpersonal issues and isn't equipped to or charged with handling this.

And I also assume you'll include an item for my comment above about updating our Resources page. Maybe I should make a new issue for that.

**Comment by sugaroverflow** [comment]
@rubyji 

1- completely agree with that. I'll rephrase the issue. 
2- yes, sorry! forgot to includethe consolidation of the resource page. I'll update the agenda :)

**Comment by sparklingrobots** [comment]
Book Club Announcement: 
Friday at noon EST we will be reading the last two sections of @vcastillo's series: https://uxdesign.cc/part-iii-why-most-conversations-in-tech-about-diversity-are-bullshit-and-what-to-do-about-it-b1db8900fce7 and https://uxdesign.cc/part-iv-equality-for-all-women-or-just-white-women-8ee3f1b58cda.  Format is again BYOQ (bring your own questions). 

DD&I Contrib team invite/update:
DDI Contrib Team has formed two teams: a front-end team focused on building a D8 theme, and a back-end team focused on converting tests to phpunit in D8. If you'd like to give back to the Drupal community in a new, d&i-focused way, please join us, whether you want to learn how contribution works or want to help others .  Just hop into the channel at #ddi-contrib-team and say hi.

We are looking for Project Managers and designers, in particular, but all are welcome!
