### ISSUE TITLE
Moving DD&I to Drupal.org

### ISSUE THREAD

**Issue by sugaroverflow** [drupaldiversity/administration#145]
We are officially moving from Github to Drupal.org! We hope this will increase engagement and make it easier for everyone to contribute. We will also have the ability to give credit on issues!  We currently have a project setup at https://www.drupal.org/project/diversity and need your help to start moving over. 

Here's what I think needs to happen: 

1. Issues
- deciding on things like tags? and maybe issue-type templates?
- asking people to move over their issues

2. Documentation/Wiki
- will probably need require some condensing of similar pages

3. Links on the website
- we will still be the `drupaldiversity.github.io` repo to push to the website, but the links for documentation or issues on the website will need to be updated to point to the d.o project. 

What other things do we need to discuss and consider?

**Comment by catch56** [comment]
With tags, can use what we like but it's better to re-use existing tags if they're relevant. To use contrib kanban (https://contribkanban.com/browse) , the 'sprint' tag is useful for things currently being worked on.

Projects can have issue queues without a code base so that should work fine, it'd be worth looking at how the Drupal core ideas queue is set up maybe but I think it's straightforward to do this from memory.

**Comment by sugaroverflow** [comment]
@catch56 looking at the Drupal core ideas queue is super helpful, thank you! I'll get back to you if I have more questions, but this is good to get started :D

**Comment by sugaroverflow** [comment]
@catch56 actually I have questions now haha. 

- what would you recommend for meeting agendas? should we have one issue for each meeting agenda - or one "meeting agenda" issue and link to the comment on the specific day's agenda? what would a meeting agenda issue be tagged?

- can we define custom components for our project? for example, we currently have `code, documentation, misc...` and the Drupal ideas queue has `idea, active initiative, proposed plan..etc` - those are really useful component tags and it would be neat if we could use those!

**Comment by sugaroverflow** [comment]
actually, I just found https://www.drupal.org/issue-queue to answer question 2 -  sorry @catch56 :)

**Comment by sugaroverflow** [comment]
Here's are my plans for the big move 🎉 

- Move over the administration documentation 
- Remove the bits about the teams and disband the teams officially. 
- Setup the components as Idea, Active Initiative, Discussion, Meeting, Moderation. 
- Move over some of my own issues as templates/examples. 
- Ask/Call out for people to move their issues over
- Update the content on the website.

**Comment by sugaroverflow** [comment]
Movement is in progress! 🎉  please start moving over your issues https://www.drupal.org/project/diversity/issues/

**Comment by agentrickard** [comment]
https://www.drupal.org/project/diversity/issues/2923896

**Comment by drnikko** [comment]
I'm going to close this meta-issue as we close out the last few items. <3 <3
