### ISSUE TITLE
Agenda for Nov 16

### ISSUE THREAD

**Issue by sugaroverflow** [drupaldiversity/administration#148]
- change of meeting time?
- DD&I Contrib team updates
- Moving to Drupal.org action items (I should have it ready for people to move issues by this meeting)
- Disbanding our teams (if the above is ready)
- What should be our protocol for when folks voice discomfort with what’s being discussed in this channel?
- DC Nashville DD&I Booth and ideas
- How we can make DC Nashville feel safer?
- personal check-ins
- DD&I anon survey form

**Comment by rubyji** [comment]
I'd like to make a general request in the meeting for people to follow us on Twitter, and engage with and RT our posts when they feel moved.

**Comment by drnikko** [comment]
As part of our move to hosting issues on drupal.org, https://www.drupal.org/project/diversity/issues/2923463

and closing this here
