### ISSUE TITLE
Official name

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#18]
Hi all,

In keeping with having a consistent logo, we also need a consistent name to reference ourselves and help others reference us.  

I (or someone else ) will be posting each of them here as a comment, and we'll choose the "winner" by the number of +1s on the comment.

**Comment by drnikko** [comment]
Name: Drupal Diversity & Inclusion
Acronym: DD&I
longer messaging (like "About Us") can still say we're a working group

**Comment by drnikko** [comment]
Name: The Drupal Diversity & Inclusion Working Group
Acronym: DDIWG or DD&IWG

**Comment by YesCT** [comment]
Working Group (with capitals) might get conflated with https://www.drupal.org/governance
so I'm cautious about that. although I like the idea of having that we get stuff done in the name.
maybe use lowercase working group sometimes, but not in the name.

**Comment by drnikko** [comment]
Points from the meeting on 1/26 (from various participants)

- I think I would shy away from DDI simply because of I/DD, an acronym for `intellectual and developmental disabilities`.  Its close enough to our sphere of influence that it might be weird.
https://crackedmirrorinshalott.wordpress.com/2011/02/11/id-dd-and-cognitive-disabilities/

- I like having D&I in the acronym because D&I is a "thing"

- I actually like saying "DD&I" because it makes me feel like I'm saying "Drupal diversity and I"

- I’m cautious of having & in the name cause … well ampersands and web sometimes cause some problems. (even though they should not)

- I don’t feel strongly about the ampersand but I like the simplicity of DDI.

- I’m cautious of having & in the name cause … well ampersands and web sometimes cause some problems. (even though they should not) - but the & might differentiate more from IDD

**Comment by drnikko** [comment]
non-conclusion update from 1/26 mtg 
It sounds like we all agree that we can use the phrase 'working group' or a non-drupal-specific synonym only occasionally and shorten to DDI or DD&I in other cases.  Our URL/twitter is DrupalDiversity which is about as short as we can get.

I'm hesitant to leave things open just because there isn't a true consensus, but I also don't know that there are better alternatives without getting too off track.  I don't feel strongly about the ampersand either, but to @cottser's point, D&I is a "thing" and a term of art in this case, for better or worse

Let's sit on it for a day or two and then make a decision.  I don't want to be inadvertently exclusionary/disrespectful/some-other-bad-thing just because we rushed.  In the meantime, we'll just call it all "Drupal Diversity & Inclusion" and be clear AF what we're doing.

**Comment by rpsu** [comment]
+1 for **DD&I** (despite the URL issues), and using **working group** about us.

**Comment by drnikko** [comment]
In the leadup to Drupalcon, we do need to decide on a name and acronym.  

It seems like we've organically defaulted to calling it DD&I, but last call for any new objections or reasons to change it?

**Comment by cleverington** [comment]
Winner: 

Drupal Diversity & Inclusion (Working Group is there, but _generally_ silent)
DD&I

## Update and Close
