### ISSUE TITLE
resources (again) 

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#19]
take these and post them somewhere and give @rootwork credit for gathering them. 
https://docs.google.com/document/d/1sgIco6Il2OX9bFKb4GiRdXlmxzy62I2k2quW98Lowiw/edit

**Comment by sugaroverflow** [comment]
I started this at DC Baltimore, but I can't find my work. 

Un-assigning myself for now because this is a good task for a new contributor.

**Comment by sugaroverflow** [comment]
@cleverington Is this something we could have someone on the technical team do? 

It might be a good task to get comfortable pulling down the site, making the markdown edits, running the jekyll serve, checking the links appear, and then making a PR?

If not, please assign me and I'll take care of it this week. Thank you!

**Comment by laughnan** [comment]
Cannot be certain, but maybe you know @drnikki. I think this was moved to: https://www.drupal.org/project/diversity/issues/2924467

**Comment by drnikko** [comment]
Yes! great!  We always want to give incoming folks a trail to follow.  thank you!
