### ISSUE TITLE
Very short mission statement(s)

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#2]
We need a few lengths of mission statement:
- one sentence
- three sentences
- paragraph

**Comment by rpsu** [comment]
I'll try with my less-than-perfect english - how is that for a start?
1. One sentence
   Diversity is versatility for all 
2. Three sentences
   The more diverse Drupal community is, the better community we have for all (of us?). Acting inclusively we invite talent in its broad sense, which brings benefits for all of us. Inclusiveness does not happen by mistake but it must be acted upon.

**Comment by drnikko** [comment]
Thanks for jumping in @rpsu!  I'd love to hear more about the intention behind 'versatility'.  Is it something like "diversity gives us options" or closer to "diversity gives us opportunities"

**Comment by rpsu** [comment]
My intention is closer to "options". The idea is that if we are somehow not inclusive as community, we also choose not to use all the knowledge and skills that we could use. l also believe that being an open, welcoming and diverse community it is easier for everyone individually to join the community - also those kind of people who are well represented currently in the community.

**Comment by rpsu** [comment]
I just realised that my assumption behind this proposal is that we somehow must try to sell the idea of diversity for someone. This is why my approach is "closer to options".

One good perspective would be to state "of course our community is diverse, and we appreciate the variation of people, opinions and subs in the name of diversity it self - it is in the core of our values".

**Comment by cleverington** [comment]
@drnikki As we are deciding on the Logo (during tomorrow's meeting?), we should move forward on Mission Statements during the meeting as well.  

I believe it might be simpler to get the one sentence Mission Statement and then create/deliver a Vision afterwords.

As for a Mission: "Creating a more diverse, inclusive, and welcoming Drupal, Community, and World."

**Comment by drnikko** [comment]
The Drupal Diversity & Inclusion Working Group (DD&I) believes that the Drupal community should be a safe, respectful and inclusive space for all technology workers. We believe that the Drupal project benefits from a diverse contribution pool, where opportunity and access are available to all.  DD&I is a collective of volunteers who work to create an inclusive infrastructure to make sure that everyone has the opportunity to participate and contribute.

**Comment by rubyji** [comment]
Great job on this, Nikki. I wanted to add something that gets at the need for proactive inclusion efforts. But I don't like what I wrote. I'm including it here in case it helps inspire any new ideas, but I like your version better.

> The Drupal Diversity & Inclusion Working Group (DD&I) believes that the Drupal community should be a safe, respectful and inclusive space for all technology workers. We believe that the Drupal project benefits from _having more diverse contributors, and we work to help the Drupal community foster a more welcoming and inclusive culture at events, online, and in our work_. DD&I is a collective of volunteers _open to people who want_ to make sure that everyone has the opportunity to participate and contribute.

**Comment by rpsu** [comment]
I do like the active approach that's included in the proposals. I think inclusiveness requires actions and that is visible here.

**Comment by drnikko** [comment]
The Drupal Diversity & Inclusion Working Group (DD&I) believes that the Drupal community should be a safe, respectful and inclusive space for all technology workers. We believe that the Drupal project benefits from a diverse contribution pool and strive to foster a welcoming and inclusive culture everywhere Drupal exists - at events, online, and in our workplaces. DD&I is a collective of volunteers who work to create an inclusive infrastructure to make sure that everyone has the opportunity to participate and contribute.

^ this is awkward, but maybe closer? @rubyji

**Comment by cleverington** [comment]
Everything looks fine to except, oddly enough, the line 'technology workers'.

Much of the Drupal goodness happens via a great deal of support from contributors and participants  above and beyond the area of 'technology. They possibly  know nothing of Drupal and, at times, could care less.  Yet representing Drupal beyond *Drupal* is important.  (Waiters, Flight Attendants, paid Event Organizers, Publicists, Investors, CEOs, CFOs, etc., etc.)

**Comment by sugaroverflow** [comment]
We compiled a short summary statement for PR #118 our statement of beliefs. 

```
The Drupal Diversity & Inclusion Group (DD&I) believes that the Drupal community should be a safe, respectful and inclusive space for all participants. We believe that the Drupal project benefits from a diverse contribution pool and we strive to foster a welcoming and inclusive culture everywhere Drupal exists - at events, online, and in our workplaces. DD&I is a collective of volunteers that works to foster a network of individuals dedicated to equitable access and to create an inclusive infrastructure to ensure everyone has the opportunity to participate and contribute.
```

With that, closing this issue. Thank you for your work on this everyone :)
