### ISSUE TITLE
Ideas for Community/Inclusion/Diversity BOF spaces

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#20]
There will be one room dedicated to community BOFs at Baltimore.  Crowd-sourcing a list of ideas for BOFs that we can pre-schedule.  There will also be slots for people to schedule their own.

**Comment by hrod** [comment]
I would like to see a BOF on How to talk about the importance of diversity and inclusion, and also how to encourage people who are not traditionally represented to get involved without being overbearing or putting too much burden on them (being sensitive to the fact that life is already difficult enough without having to be the go-to person to represent a particular group all the time).

**Comment by sparklingrobots** [comment]
Ideas:

- a BoF on managing imposter syndrome.  
- I second hrod's idea of a BoF about encouraging less represented people--I'd like to talk strategies about ways to inclusively mentor/support people looking to enter the field. 
- Perhaps a general networking/social BoF for those interested in inclusion/diversity issues.  Sometimes I feel like I'm the only one, but I know that's not true!

**Comment by cleverington** [comment]
Just to prevent Imposter Syndrome for new participants making plans:

https://www.drupal.org/docs/7/understanding-drupal/glossary#bof

> BoF #

> Birds of a Feather (BoF) refers to an informal discussion group. Unlike special interest groups or working groups, BoFs are informal and often formed in an ad-hoc manner. BoF meetings are common adjuncts to planned "sessions" at Drupal camps and at DrupalCons

**Comment by amandagonser** [comment]
I am really loving these ideas!  Please keep the brainstorming coming.  These can be topics to discuss or a space for specific communities to meet each other as well - like dis/abled in Drupal.  Thank you for your inclusivity.

**Comment by jordanpagewhite** [comment]
It might be cool to have some kind of space or some way to connect to people who either do not work for a big Drupal shop that can send a group of people, work out of a non-tech city (i.e. not SF, Oakland, Portland, etc.), or just generally need people to connect to. I went to my first Drupal event recent (BADCamp), and I had an amazing time. But, coming from a small(er) city with a small tech community and since I do not work for a big Drupal shop, I did notice that there were packs of Acquia folk, Chapter3 folk, Four Kitchens, etc. etc. etc. I still talked to people and had a good time meeting people, but if there is a way to reach out to the introverts (like my coworker for ex.) it might improve their experience, retention at future Drupal events, and hopefully inspire them to get involved in volunteering at future Drupal events.

**Comment by sparklingrobots** [comment]
Another idea: How to increase diversity and inclusion at our local meet-ups.

**Comment by rohit-jha** [comment]
Is there any such group for INDIA location  ?

**Comment by drnikko** [comment]
Several people have suggested a BOF only for those who identify as female.  Some suggested having it as sort of a pre-mixer before the evening event to make that event more productive.  Others have suggested having it immediately after so people can followup with connections from the night before.

**Comment by sparklingrobots** [comment]
These ideas are a bit half-baked but as we were discussing some of these subjects in the Slack channel today, I'll share them anyway: 

- What about a friendly code review BoF? Set some rules in advance about how to give good, encouraging feedback (e.g. not condescending feedback).  Receiving friendly feedback and having the opportunity to give feedback can build a lot of self-confidence and combat imposter syndrome.   
- What about a job fair (for lack of a less cringe-inducing term)?
- Peer resume review
- Money management
- How to negotiate with employers

**Comment by cboyden** [comment]
There are at least three diversity/inclusion related sessions accepted, how about planning a general BOF to start right after one of the sessions?

**Comment by drnikko** [comment]
The community space BOF schedule is up!  If there are any we wanted to see that didn't make it, we can schedule them individually.  Thanks, all, for the contributions!
