### ISSUE TITLE
DrupalCon Baltimore Booth

### ISSUE THREAD

**Issue by cleverington** [drupaldiversity/administration#21]
## Issue

Call for requests/ideas re: Drupalcon booth.  We have a hard deadline of 2/10 to make any formal requests for extra things beyond a table and two chairs.

**Comment by drnikko** [comment]
from Alanna - alannaburke [< 1 minute ago] 
This is more of an idea of what we could do at the booth - what if we riffed on the “this is what an engineer looks like” and had a “this is what a drupaler” looks like - we could take polaroids (or whatever they are these days) of diverse folks who come by the booth (who are comfortable with it, of course!) and post them up in a collage behind the booth, to show how diverse the drupal community is in a visual way.

**Comment by AlannaBurke** [comment]
If this is something we want to move forward with, I'd be happy to research tech we could use (photo printers, etc)

**Comment by sparklingrobots** [comment]
If photo printers are prohibitive, maybe some kind of a #thisiswhatdrupallookslike hashtag and a large screen displaying everybody's posts? 

I also wonder about plain old paper--people writing down what they want to see from the Drupal community, problems they've faced re: diversity & inclusion, good ideas, things they want to take back to their workplace or community, etc. I like the basic idea from drnikki about people being able to contribute to the booth itself. Also I hate talking to booth people but will totally do an activity if one is presented. :)

**Comment by sparklingrobots** [comment]
I don't think this is related to the 2/10 request deadline, but what about stickers? Do we have any art assets that represent this group?

Edited to add: I'd be happy to do the work to get these set up for printing, btw.

**Comment by drnikko** [comment]
@AlannaBurke it would be GREAT if you could take the lead on figuring all of that stuff out.  I've put in a request for power and a monitor at the table.   Made an issue for this specifically #23

**Comment by drnikko** [comment]
Closing this, because we are doing a GREAT job!! We figured out nearly all of our booth stuff!
