### ISSUE TITLE
Drupalcon booth photo setup

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#23]
We need to figure out what options we have for running an "I'm a Drupaller" photo campaign. 

We will likely have power/monitor at the booth.  
We have a drupaldiversity instagram account.  
I have an ipad I can bring...

**Comment by sugaroverflow** [comment]
This idea might be totally out of budget, but an on-site photo printer? It's more fun to a picture at an event with some kind of instagram-y frame (and hashtag) and be able to take the photo with you. :)

**Comment by AlannaBurke** [comment]
@sugaroverflow That's actually what I was thinking - though i was thinking to pin up, but handing out something branded would be awesome! I'm going to brainstorm on the money angle - i think if we can present it to just a couple companies (I said in the meeting that I could probably get mine on board) we could easily fund this). We're talking a photo printer and paper, some props - nothing extreme.

**Comment by sugaroverflow** [comment]
@AlannaBurke I think that's a great idea! 

There must be a way to get the insta-frame on the polaroids/printed photos automatically, but if there isn't, we could probably pin up something and people can take digital photos too if they really want to.

**Comment by drnikko** [comment]
@AlannaBurke just wanted to follow up on this?  Do you have an update for us and do you need any help?

**Comment by AlannaBurke** [comment]
@drnikki I'm working on it! There are so many options! I'll narrow it down and get something to you this week.

**Comment by drnikko** [comment]
<3

**Comment by star-szr** [comment]
Can we (with their permission of course) keep a copy of the photo for our booth and make some kind of display out of the photos? Some kind of mosaic/collage/similar.

**Comment by AlannaBurke** [comment]
Okay, here is my plan:

I'd like us to have some kind of banner or sign that says "This is what a Drupaller looks like" (or similar) to attract folks.

We'll use mobile devices to take folks' photos, aiming to capture a diverse crowd. We can use an app that allows us to add a label/border to printed photos- "This is what a Drupaller looks like, " DD&I link, a hashtag, DrupalCon 2017, etc.

With the photos (and permission) we will:
- Print and hang up as a collage
- Upload to DD&I Instagram
- Offer a print to people - serves as souvenir and marketing

We could also have some photobooth props (big sunglasses, hat, scarf), for people who want to participate but don't really want their photo out there.

Looking into technology, I think our best bet is the [Fujifilm INSTAX SHARE SP-2](https://www.amazon.com/Fujifilm-INSTAX-SHARE-SP-2-Printer/dp/B01GTKG6RA/ref=dp_ob_title_ce). It will allow us to do all of the above, including creating templates, reprinting photos (printing one for us and one for them), and printing on sticker film. ([Instax Mini Instant Film](https://www.amazon.com/Fujifilm-Instax-Instant-Packs-Pictures/dp/B00O4OR4GQ/ref=pd_sim_421_2?_encoding=UTF8&pd_rd_i=B00O4OR4GQ&pd_rd_r=J7BNHKY7HBW8M4Y40R0H&pd_rd_w=EoXmQ&pd_rd_wg=jED9S&psc=1&refRID=J7BNHKY7HBW8M4Y40R0H)). No ink is needed. After they print, they develop in a few minutes like Polaroids, which is also fun. The downside is, this film isn't cheap, but if we could get some donations as suggested in the chat today, that would really help offset the cost. I think with a couple donations (heck, I'd happily pitch in), we could pull this off and have a really fun way to interact with people, and give a great visual of Drupal's diversity. 

Next steps:
Figuring out how to fund this, and buying it! We need to buy the printer ($162.10), and figure out how much film we want/need, and purchase that as well.

**Comment by drnikko** [comment]
@AlannaBurke thanks so much for researching this.  I have an ipad mini we can set up at the table as a picture-taker. 

Do you feel comfortable leading the charge on getting this funded, and/or how can I/we support you?

**Comment by AlannaBurke** [comment]
@drnikki I can take the lead! Here are my thoughts:

- decide how many pictures we'd ideally love to take so we can be prepared
- get a rough estimate of how much $$ we need
- put together a nice little pdf proposal that we can send to camps/companies/friends asking for donations

Do we have a way to accept donations currently? If not, we'd want to get that in place (i think paypal would be fine)
Anything major I'm missing?

**Comment by mikemiles86** [comment]
This is a great idea and a fun way to have people interactive and think about diversity.  

Knowing that we'd like to implement a fun way to take digital photos I reached out and proposed an idea to the upper management of my agency ([Genuine](www.wearegenuine)) to see how we can help. I have received approval to provide the Drupal Diversity group with the following for Drupalcon:

We have an internal product called PhotoOpp which we've sold to clients for use at live events. PhotoOpp uses a custom IOS App to take photos with a custom border, design, etc...  (For a campaign we did with Norton Antivirus your picture had you dressed up like an Avenger. For Facebook it had you wearing an Oculus).  Each picture taken comes with a custom retrieval code (which can be emailed) and participants can use to view and print out their photos online.  The online piece is built on top of a Drupal 7 backend.

Genuine will provide the internal resources needed to setup a new PhotoOpp engagement for the Drupal Diversity group. This includes getting the app and Drupal site prepped for Drupalcon, as well as, help with getting photos uploaded at the end of each day (I'd be doing this).

If this is something our group would like to use, I can continue getting my internal resources scheduled and let you know what the group needs to supply.

**Comment by AlannaBurke** [comment]
@mikemiles86 Thanks for reaching out! This sounds cool - I like the retrieval code option. My only concern is how it would fit into the workflow with the printer we plan to use - it also has an app with similar functions, but isn't designed for events, and AFAIK doesn't have any kind of retrieval code. I haven't used the app yet, but I'm wondering if we could figure out a workflow to take the pictures with PhotoOpp and then still send them to the printer.

**Comment by mikemiles86** [comment]
@AlannaBurke great question and valid points.  I will check with the team who built PhotoOpp to get a better understanding of what it does with the photos once taken. My current understanding is that the photos are stored locally and then are batch uploaded to the web at a later time. If the app with the printer allows for printing existing photos (not ones taken with the app) that may allow for using both apps.

**Comment by rubyji** [comment]
@mikemiles86 Does your tool tie in to Instagram or anything similar? I think one of the important parts about this effort is publicly sharing the images in a social way to promote the idea of all these numerous and diverse people being a part of Drupal. By posting them (when people agree) in real time we can take advantage of the person's energy and momentum. They're more likely to share it with their own networks right after talking to us. And then that keeps the engagement going.

**Comment by mikemiles86** [comment]
@rubyji I will add that to my list of questions to ask the PhotoOpp team, and provide an update when I hear back.

**Comment by lpeabody** [comment]
Hi folks, I work with @mikemiles86 at [Genuine](https://www.wearegenuine.com/) and he asked me to provide some insight into what we you can expect from our FotoOpp application.

Essentially what we'll be able to do is provide a set of image overlays, take a photo with the overlay applied (think Snapchat), and store that photo locally on the device and also upload it to the web. Once uploaded, the photo would be accessible on a custom designed page for the event with sharing functionality attached. Since the photo would also be stored locally on the device you would also be able to reuse the photo to upload to Instagram or use in any other application running on the device.

One thing to keep in mind is that the uploaded files are not guaranteed to live forever, but to my knowledge we've never deleted any uploaded photos. That is to say, we have no set policy on permanent file storage. It's possible that you could share a photo, 5 years down the line we delete it, and your "On this day 6 years ago you were having a Drupalrific time" memory from Facebook will be missing the photo, which I've always considered acceptable because a user can always download the photo and upload to Facebook directly (we provide a big download button).

An example photo page can be seen at http://facebook.fotoopp.co/facebook/phoenix-airport/ct5nbpj2. In this instance we applied a custom GIF overlay (this is not native functionality and was specially designed for Facebook, our instance would include just static imagery).

I'm happy to answer any questions folks might have about the application and how we can use it to our advantage in spreading the good message of this organization. If this is something we decide on using, happy to support the effort.

Cheers,
Les Peabody

PS - @sugaroverflow can't wait to hang at DrupalCon!

**Comment by drnikko** [comment]
I'm going to defer to @AlannaBurke for how she envisioned this process and the technology she'd like to use.  I'm so excited to see all the contributions and discussions of this and I think it's going to be so cool to have at drupalcon.

**Comment by AlannaBurke** [comment]
Let's move forward with PhotoOpp (thanks @mikemiles86 and @lpeabody)

We'll make sure everyone consents to having their photo taken ( #29)

I will finish up a proposal for funding by tomorrow!

One question - does anyone have a thought on how many photos we'd like to be able to take? I'd rather fund and have an extra case of film than wind up running to best buy six times during the conference or running out.

**Comment by AlannaBurke** [comment]
- [ ] Find out where we can get film in the Baltimore area if needed

**Comment by bendygirl** [comment]
@AlannaBurke I'm local and commuting everyday, so I can handle additional film if needed. The number of photos should be based on expected foot traffic. If Drupalcon pulls in say 2500 attendees (possibly more), then we could estimate a drop in attendance in the exhibit hall of say 20 to 30% (based on typical foot traffic) which would be about 1800 to 2000 potential pictures. Probably less since not everyone coming into the hall will visit the booth. Seems likely we'd be looking at a slightly higher drop than 20/30 which seems appropriate to estimate about 1000 overall willing to come to the booth and potentially wait in line to participate.

So, about 1000?

**Comment by AlannaBurke** [comment]
@drnikki First draft - thoughts? https://docs.google.com/document/d/1An1pHVo9WlRVe5oAyi6gw3-8CaYa62Kbi3vSypgBaXo/edit
I think if we send this to enough folks/companies we can raise this quickly, especially if people just want to send in a roll of film. I'm also happy to buy the printer and just do this with however much film we get and if it's a flop, we just do it again next year!

**Comment by drnikko** [comment]
@AlannaBurke I love this. And we have letterhead now! :)  :) 

Do you think it might make sense for us to set up an Amazon wishlist?  That way people can just purchase film and have it sent somewhere.  That way people won't have to worry about finding the right film themselves.

**Comment by AlannaBurke** [comment]
Yes, that would be perfect! I'm happy to handle that, unless you want to.
Are there any rules we should be following here, financially?

**Comment by mikemiles86** [comment]
So I've started to get resources going on the Genuine side to get our instance of FotoOpp setup.  A few things I need from the group.

1. The way the domain is setup, is as such: fotoopp.co/[client]/[event]/[photoid]

We need to figure out what we'd like the client and event name to be. I'm recommending keeping it simple and going with "drupalcon/baltimore"  so our urls would be fotoopp.co/drupalcon/baltimore.

Thoughts?

2. When users go to retrieve their photos online, they will see their photo on a basic styled page. Here is an [example](http://fotooppcoygkucuagmb.devcloud.acquia-sites.com/jack-morton-worldwide/acquia-engage/2funek) of an event we did for Acquia Engage. For our landing page, we need to outline what the page title, will be (DD&I Drupalcon Baltimore 2017 ?).

3. On that page we can change some of the basic styling (not much of the page layout). At the very least I think we need to create a background with either the Drupal logo or our logo.

4. When an image is taken with FotoOpp an overlay will be applied. Based on the discussions above the current idea (As I understand it) will be to have it look like a polaroid picture with the words "This is what Drupal looks like".  We can have the overlay be anything we'd like as long as it is a transparent png. Where the transparencies are is where the photo that is taken will be show.  

I am no designer, but I took a stab of creating an overlay. I'm sure someone can use this as inspiration to produce something of better quality.

Overlay:
![polaroid_overlay](https://cloud.githubusercontent.com/assets/196745/24383507/3da02bc0-132b-11e7-81cd-89c6a3ecc933.png)


Example image:
![polaroid_example](https://cloud.githubusercontent.com/assets/196745/24383509/42afeca4-132b-11e7-808d-171ffd2bcb98.png)

(I understand having a 30 something white male as the example photo does not much show diversity or inclusion. But you work with the self-model you've got :-P)

**Comment by AlannaBurke** [comment]
@mikemiles86 Thanks so much for your work!

Could we have the url be drupalddi/baltimore? I want to make sure we're clear that we're AT DrupalCon Baltimore, but this is for Drupal Diversity & Inclusion.

As far as styling, we've got our [logo](https://github.com/drupaldiversity/administration/tree/master/assets), and we've used 
this background header image on our [twitter](https://twitter.com/drupaldiversity) that I like, so if we could incorporate that - great. 
![ddi_bg](https://cloud.githubusercontent.com/assets/1540998/24417751/96fcac70-13b7-11e7-9991-4fbe6a1835d4.jpeg)

Thanks for the work on the photo overlay - I'll grab that and take a stab and polishing it up!

**Comment by AlannaBurke** [comment]
@drnikki If you get a chance today, can you take a look at the comments i left on the doc? I'm hoping you can answer those questions. I'll set up an Amazon wish list (think it's ok to just set it up under my amazon account?) and edit the text to reflect that. Let me know if there's anything else I should add or change, and then we can start sending this around!

**Comment by sparklingrobots** [comment]
Maybe I'm paranoid but I've been wondering how this could be 'hacked' by the users (from prior experience with crowds + technology). I wonder about visitors wanting to share their own messages under the dd&I auspices, and whether or not that is okay with us. What about people with signs/t-shirts with slogans?  Maybe all images have to just be shoulders up? I don't know but it will be easier to think about this now than in the midst of the con if something unanticipated happens.

**Comment by AlannaBurke** [comment]
@sparklingrobots these are good thoughts! We are taking the photos, so we can control what is in them - I agree with shoulders up - at least as far as we can, there could be group photos, but i think we can handle that on a case to case basis. I also agree that we can discuss what would constitute a slogan, etc, though I don't anticipate a problem there, it is definitely something to be aware of.

**Comment by sparklingrobots** [comment]
@AlannaBurke It's just easier for a volunteer to say, "Sorry, can't include your sign, it's a policy" than for that volunteer to have to make the call on the spot.  I think it will mostly be okay but since it crossed my mind, I wanted to share.

**Comment by AlannaBurke** [comment]
@sparklingrobots Agree, we should talk about it so that we can make a clear policy just in case.

**Comment by mikemiles86** [comment]
@AlannaBurke Thank you for the feedback. I have the PSD for the polaroid I created, let me know if you'd like that.

I used the logo and twitter background image to produce a quick mock-up:

<img width="500" alt="ddi_drupalcon_mock1" src="https://cloud.githubusercontent.com/assets/196745/24423264/62d8e216-13ca-11e7-86c1-60dca8d55b6c.png">

I think the background is very very vibrant when applied over such a large area. Perhaps we might want to "mute" it a bit in this instance? (quick mock up)

<img width="500" alt="ddi_drupalcon_mock2" src="https://cloud.githubusercontent.com/assets/196745/24423276/6cf5811e-13ca-11e7-99e1-d078a03144db.png">

I also tried to see what it might look like applying the logo as a repeatable background.

<img width="500" alt="ddi_drupalcon_mock3" src="https://cloud.githubusercontent.com/assets/196745/24423289/73c3f5b6-13ca-11e7-9f8e-09b587832db8.png">

We also have control to set the intial twitter message sent out, if the visitor chooses to share their image that way.  The default message would be something like "Here is my Photo from Drupalcon and @drupaldiversity".

**Comment by AlannaBurke** [comment]
Ooh, yeah, it's a little bright. It definitely looks better as a header. What are the recommended dimensions? I can put something together using the rainbow as a header or footer on a white bg, and we could set the whole thing as a bg image.

The logo looks great! I'll think about what the social media messaging should be, we definitely want to customize that. 

Thank you!

**Comment by drnikko** [comment]
Closing this along with #36.  Will defer to @AlannaBurke if we need new issues for tracking new tasks.  Thank you everyone for your work on this - so stoked to have it funded and to be able to do this in Baltimore.
