### ISSUE TITLE
Sticker image

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#24]
It's sticker time!

We'll need an SVG or AI file of the logo with some identifying text on it.  We can absolutely get the stickers die-cut, so we just need to figure out if we want the twitter handle (probably best - people can just follow us on the go) or some other text on it.

It seems that the turnaround time is pretty fast, so there's not a real rush on this - mid/end of March is probably fine.

Just wanted to get this in the queue. :)

**Comment by drnikko** [comment]
Hi @Cottser, do you think we can have a sticker image by next week?  We'll be getting die cut stickers from Custom Sticker Makers (at @rubyji's suggestion).  Everyone is on board with the logo (thank you again for that) we just need to add our twitter handle (probably?) to it or some other text-based identifier.  

You can scope out the stickermaker details here: https://www.customstickermakers.com/index.php?main_page=index&main_page=product_info&cPath=1&products_id=1

**Comment by star-szr** [comment]
Hi @drnikki, thanks for the bump and the link! This has been on my mind for sure.

I'll try to put together some different options or at least one along the lines of what we've been discussing to date.

**Comment by star-szr** [comment]
Feedback on this overall design, please :) I'd need to make some refinements to the details if we go with this.

![sticker - twitter handle](https://cloud.githubusercontent.com/assets/327943/24073364/4694241c-0bcd-11e7-8fca-971c307ccc87.png)

![sticker - twitter handle - small scale](https://cloud.githubusercontent.com/assets/327943/24073395/938211f8-0bcd-11e7-8709-b2f1d05e0b20.png)

[Sticker - twitter handle.svg.txt](https://github.com/drupaldiversity/administration/files/852531/Sticker.-.twitter.handle.svg.txt)

**Comment by drnikko** [comment]
Awesome, thank you for doing this!  I had pictured our twitter handle at the bottom, only because I think of it as reading from top down - a picture which begs the question "what is this?" and then the handle as the answer, but I am still not a designer and am happy to defer to majority opinion.

**Comment by rubyji** [comment]
I'd love to see if we can also try the handle on the bottom-right border of the heart. Is there any way to get "Drupal Diversity & Inclusion Working Group" on there without looking ridiculous? Or maybe it could be printed on the sticker backing?

**Comment by mikemiles86** [comment]
I agree with @rubyji on moving the handle to the bottom-right border.

**Comment by star-szr** [comment]
I tried that and I wasn't happy with it but maybe it was my execution. I'm out right now but I'll try to upload a version like that later.

**Comment by star-szr** [comment]
I went back and tried a slightly different approach and I like this one a bit better. Feedback, please!

![sticker - twitter handle - bottom right](https://cloud.githubusercontent.com/assets/327943/24086708/02eefefc-0ceb-11e7-8516-5e8e0934f6d9.png)

![sticker - twitter handle - bottom right - small scale](https://cloud.githubusercontent.com/assets/327943/24086709/05a6cd78-0ceb-11e7-8466-4d35d820512c.png)

[Sticker - twitter handle - bottom right.svg.txt](https://github.com/drupaldiversity/administration/files/853768/Sticker.-.twitter.handle.-.bottom.right.svg.txt)

**Comment by rpsu** [comment]
I personally like the earlier version better, with the text being on the top of the heart and bending with the edge/border.

**Comment by rpsu** [comment]
Now, the next question is - when can I order these? :)

**Comment by sugaroverflow** [comment]
Personally, I like the first version with the text on the top curve.

**Comment by sparklingrobots** [comment]
I'm a fan of the text on the bottom, but they're both great. Is it on a gray background or is that just the "non-sticker" area?

**Comment by star-szr** [comment]
The grey background is just the non-sticker area, because GitHub has a white BG :)

**Comment by hrod** [comment]
I like text on bottom, but no strong feelings.

**Comment by rubyji** [comment]
I like both options about equally. Thanks for trying the alternate side, @Cottser.

**Comment by drnikko** [comment]
@Cottser I'm going to defer to your artistic vision on this one. ;)  We need a 300dpi image as soon as possible.  The vendor is saying 10-14 shipping days, so I want to make sure there's time for it to get to my house and into my suitcase so I can bring them to baltimore. 

do you think we could have a full-res image in a few days?

**Comment by star-szr** [comment]
@drnikki cool. Yes, I can have it for you within a few days, it sounded like SVG would work. I'll try to get this to you tomorrow to allow for some back-and-forth.

Also, do you know how big the stickers will be? In my mind it would be something like 2.5-3 inches tall but I want to make sure that I consider the physical size this will end up before finalizing things.

**Comment by lauras** [comment]
I really like it!

**Comment by drnikko** [comment]
@Cottser I had pictured it about 2 - 2.5" wide at it's widest part, and however tall that makes it - we can set a specific size through the vendor so will defer to you on preferred dimensions when we order.

**Comment by star-szr** [comment]
The votes were split (I checked Slack too), and I think the version with the twitter handle on the top will work better for the die-cut process since there needs to be some allowance for discrepancies. So here's an updated version of that.

I printed out some stickers at home and a size of 2–2.25" wide should work well. The overall shape is almost exactly square, so the height will be about the same.

@drnikki please ping me on Slack if you need anything!

![top right - v2](https://cloud.githubusercontent.com/assets/327943/24639473/d6e3a7c0-18bd-11e7-86cd-e3360cd29985.png)

![top right - v2 - small scale](https://cloud.githubusercontent.com/assets/327943/24639478/d99a8902-18bd-11e7-87cb-3c08076d5e8c.png)

[Top right - v2.svg.txt](https://github.com/drupaldiversity/administration/files/891930/Top.right.-.v2.svg.txt)

**Comment by star-szr** [comment]
The stickers arrived, so closing. Thanks for the feedback, everyone! 🎉
