### ISSUE TITLE
Can we add our logo to this GitHub organization?

### ISSUE THREAD

**Issue by rubyji** [drupaldiversity/administration#26]
It will look cooler on my GitHub profile that way. ;-)

**Comment by star-szr** [comment]
Agreed :) I think at this time @drnikki might be the only person with permissions but I'm not super familiar with GitHub organizations.

**Comment by cleverington** [comment]
Yes. Only @drnikki (the Organization Owner) can change the 'Profile' via the following steps:

1. Clicking her icon at the top right and selecting 'Settings', 
2. Clicking on the drupaldiversity organization at the bottom-left (below the other options we all see) within the **Organization Settings** box
3. Updating the DrupalDiversity Organization Profile.

;-)

**Comment by drnikko** [comment]
All done!  Thanks for catching this, everyone!  @Cottser I just grabbed the 300x300 image off the issue.  Reopen if you'd like me to use something different.

**Comment by rubyji** [comment]
Thanks, @drnikki! It might look even better with a transparent PNG rather than the white background, but I'm glad to have it there. It looks great.

**Comment by star-szr** [comment]
Here's a transparent 300x300 for testing.
![logo - transparent 1x](https://cloud.githubusercontent.com/assets/327943/23616492/e9e8c08e-0257-11e7-81c8-dafdc643cd89.png)

**Comment by drnikko** [comment]
@Cottser just updated to transparent - good call!
