### ISSUE TITLE
Scholarship to recruit new talent to the Drupal community

### ISSUE THREAD

**Issue by hrod** [drupaldiversity/administration#27]
In order to increase our diversity efforts, can we tap into existing structures to create a fund that would be used to attract diverse candidates to our events, pay for trainings, and anything else that would help people overcome the barrier to getting into Drupal?

**Comment by catch56** [comment]
There's https://events.drupal.org/baltimore2017/grants-and-scholarships for specifically getting people to DrupalCon.


There's also https://www.drupal.org/association/community-cultivation-grants which might be able to help trainings/events.

**Comment by rubyji** [comment]
@catch56 We actually discussed the existing Drupal scholarships at the time this suggestion was made, and I think the distinct idea with this is to bring in people who aren't already involved in Drupal. 

I was on the scholarship review committee this year and I think we need to do a *way* better job of recruiting applicants that will actually contribute to the diversity of the community.

**Comment by sugaroverflow** [comment]
We're moving to drupal.org #145 
@hrod If you're still interested in continuing the discussion on this, could you please move the issue to our d.o queue and then close this issue? https://www.drupal.org/project/issues/diversity

You can also choose to close or ask me to take care of it :) Thank you!

**Comment by drnikko** [comment]
I'm going to close this @hrod and if you want to open in d.o please do.  There is overlap here with the Palantir inclusion initiative too, so that's something to keep in mind.
