### ISSUE TITLE
Photo Booth Privacy Statement

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#29]
In a thread re: the photo booth and sharing: "we should come up with something brief that says how this photo will be used and what they are consenting to by having their photo taken. (ie, putting it on instagram)"

**Comment by AlannaBurke** [comment]
@drnikki Do we plan to use these photos anywhere but instagram? 

If not, I propose something like this, maybe printed out and laminated and we'll put it by our little photo station, however that is set up.

> By having your photo taken, you consent to allowing Drupal Diversity & Inclusion to display this photo on social media, and display the printed photo as promotional material in a booth setting.

**Comment by drnikko** [comment]
@AlannaBurke I think just instagram and however we put them up in the booth.  Certainly open to other ideas, but want to keep people feeling both safe and seen.

**Comment by AlannaBurke** [comment]
How's this?

https://docs.google.com/document/d/1UuIjzQG_bJ0_aGOddqD_5BrQXBeFj6kE_t9mowQOniU/edit?usp=sharing

**Comment by sparklingrobots** [comment]
@AlannaBurke Is it possible to include a mock-up of what the social media posts would look like? Just...given all the recent drama on social media I might be wary, but if I saw that it was my face with a "This is what Drupal looks like" caption or something, I'd feel a-okay about that. 

Edit: Just saw the mock-up on the other thread and thought that could be useful.

**Comment by AlannaBurke** [comment]
@sparklingrobots we do have that mockup - do you think it should be added to the privacy policy? that's probably just going to be printed and sitting on the table, where there will presumably already be some pictures that we've taken of ourselves that we can show. We could also add a mockup to the funding proposal (i got confused with github posts and originally read this comment thinking that's what you meant, and now I think it might be a good idea).

**Comment by sparklingrobots** [comment]
@AlannaBurke I was thinking it would be a useful visual for what we intend on the privacy policy.  You're right though that we will have some examples in the booth so perhaps it's overkill. 

Didn't think of adding it to the funding proposal but I don't know, maybe? I'm always in favor of visuals when trying to make a sale. :)

**Comment by AlannaBurke** [comment]
Note: we may make the instagram private given the current social media climate. To be decided. 

We may also ask people if they are okay with their photo being in the closing session, and if they say yes, put it into a separate album, and create a few google slides.

**Comment by AlannaBurke** [comment]
Updated: https://docs.google.com/document/d/1UuIjzQG_bJ0_aGOddqD_5BrQXBeFj6kE_t9mowQOniU/edit

**Comment by AlannaBurke** [comment]
Add foto opp!

**Comment by AlannaBurke** [comment]
This is done and printed - i decided to let fotoOpp be covered under 'social media'
