### ISSUE TITLE
Explicit leadership roles & appointments

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#31]
The amorphous structure of the DD&I group - if you show up, you're part of us - is wonderful.  So many people have commented lately that leaders should be held to a different (higher?) standards than community members.  If this is the case, for the DD&I group, we'd need to first define who the leaders are and what their responsibilities are.  

This issue is for that!

**Comment by rubyji** [comment]
I missed the conversation in Slack around this, but this might be a good goal for our second year as a group. I can see having a chair/lead organizer, vice chair(s)/organizers, and project leaders - something along those lines. Maybe a steering committee.

**Comment by cleverington** [comment]
Based on recent events, I'll bump a prop on this issue to review it during our Weekly Meeting to create a Steering Committee for Moderation purposes.

**Comment by lyndsey** [comment]
In the first instance perhaps identifying a few "Ask [name] about..." people and pinning it in Slack would really help? It can help to flesh out some roles and conversation topics too. For example:

Ask [name] about the group aims and what we want to achieve
Ask [name] about how to get involved and help
Ask [name] about finding resources for your organisation
Ask [name] about increasing diversity at your next conference or event

**Comment by drnikko** [comment]
We discussed this explicitly in the strategy meeting (full notes in #28), and the relevant parts here are:

DDI has the same problem as the community. Should we lead by example? Consensus: yes
- Roles should allow people outside to understand who to talk with.
- Be clear about roles and responsibilities.
- If you want a 501, you have to have them, although that’s not a rush.
- Helps new arrivals understand who gets listened to more than others.
- How to handle people who don’t have/need formal role, but have a strong voice?
- There appears to be a clear need for teams like the moderation team.
- there should be individuals for accountability and teams for support of those individuals.
- Use the status emojis for roles to help support roles, or put the role in name.
- Teams are Taxonomy based
- Put something into the issue queue so we can attract people who are not here.

Initial Teams:

- Moderators
- Communications
-- Web site
-- Twitter
-- PR
- Leadership
-- Chair
-- Vice Chair

Initial Members:

**Communications**
Scott
Ruby
Alanna
**Leadership**
Nikki
Ruby
**Moderation Team**
Alanna
Kara

Solidification By: Ruby and Alanna

**Comment by sugaroverflow** [comment]
Linking the collaborative doc of teams and volunteers: https://docs.google.com/document/d/1E24reX_62IgRAYlq97v9McDDc1fT-Jc4hqMlb7FxciM/edit#

**Comment by YesCT** [comment]
Administrative roles and organizing (around moderation) sound different than taking moderation shifts... the doc here I think is more of the admin org.

Use https://github.com/drupaldiversity/administration/issues/69 to volunteer for being a moderator.

**Comment by drnikko** [comment]
We did create teams!  Like mentioned above, use #69 to become a moderator.  Team leadership was announced in the May 11 meeting - agenda and notes in #65
