### ISSUE TITLE
Update Drupal Diversity Instagram logo

### ISSUE THREAD

**Issue by AlannaBurke** [drupaldiversity/administration#35]
https://www.instagram.com/drupaldiversity/

Since we're including its existence on our funding proposal, it should look like it's real!

**Comment by drnikko** [comment]
I did a thing on the same day that it was assigned to me!!

https://www.instagram.com/drupaldiversity/

Thanks for catching this!!

**Comment by drnikko** [comment]
But also just realized that it's not centered... brbbbbbbbbbbbbbbb

**Comment by drnikko** [comment]
Okay, I can say with confidence that this is above my pay grade.  Up to you @AlannaBurke if you want to see if @Cottser can make it look less dumb.  I for sure can't. :)

**Comment by AlannaBurke** [comment]
@Cottser If you get a chance, can you make a square version of the logo that's centered, about 200px? It's looking off in instagram's circle logo:
<img width="233" alt="2017-03-28_1436" src="https://cloud.githubusercontent.com/assets/1540998/24421388/08d16b18-13c4-11e7-8f56-41d6fb0dc0b6.png">
Thank you!

@drnikki you tried, we'll pass it back to the design team!

**Comment by star-szr** [comment]
Sorry, I missed this mention, but try this (first a screenshot in Instagram's web UI, then a JPEG to upload to Instagram). Feedback definitely welcome :)

![image](https://cloud.githubusercontent.com/assets/327943/24656460/ab78eaa2-1910-11e7-8fd9-b7d71393024e.png)

![logo - instagram 2x](https://cloud.githubusercontent.com/assets/327943/24656466/af8d287e-1910-11e7-888a-8d4ed8396fd4.jpg)

**Comment by AlannaBurke** [comment]
@drnikki can you give this a go?

**Comment by drnikko** [comment]
@Cottser++ perfect 
@AlannaBurke thanks for the ping
https://www.instagram.com/drupaldiversity/ 

Please reopen if we need to tweak it further. <3
