### ISSUE TITLE
Explicit definitions of what DD&I means when we talk about diversity and inclusion

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#37]
As we work on what we want to "include" and who we feel comfortable excluding (Nazis seem to be a fallback everyone can agree on), we should also make sure we're crystal clear about what we mean when we talk about diversity and inclusion.

**Comment by catch56** [comment]
I'd like to see accountability added in here as well. I haven't done a lot of reading on it, but for example http://www.creativeconflictresolution.org/jc/maps-1/radical-accountability.html

**Comment by johnshortess** [comment]
I've got some ideas on expanding this to a short "What is Diversity and Inclusion?" primer document, that could be used as a website intro page or a booth one-sheet. My goal is to make it as welcoming and non-threatening as possible, and light on jargon like 'privilege' that might induce knee-jerk reactions. (We can introduce those concepts later in more in-depth documents, but the people who are going to have knee-jerk reactions like that are some of the people we _really_ need to reach, and we don't want to make them stop reading on the very first page.) I'll incorporate ideas from here and Slack, and try to get an initial draft into a Google doc sometime this weekend. Specific suggestions are welcome!

**Comment by drnikko** [comment]
@hrod just wanted to make sure you saw this so you didn't duplicate efforts. Love all the work that everyone is putting into this. <3

**Comment by johnshortess** [comment]
@hrod Happy to coordinate/collaborate! I was multitasking this afternoon, so might have missed Slack discussion of what you were doing.

**Comment by hanoii** [comment]
I've been thinking about this, however, my thoughts went into creating a comprehensive FAQ. Was about to create a new issue, but found this one and it's closely related. From the recent incident and the following I tried to do on the channel it seems that questions I had/have and others appeared a few times.

While I well written document is OK, I think a nice/comprehensive FAQ is much more welcoming for the general audience and one most developers are very used to seeing.

Just an idea.

**Comment by sugaroverflow** [comment]
Closing this issue because we've explicitly defined our values as a group in our statement of values in #118  - thank you everyone for your help to put that together!

However, I think the idea of having an FAQ or a primer document of "What is Diversity and Inclusion" in general (and not just specifically for this community or group) is a fantastic one - and I think that needs it's own issue so I opened a new one: https://github.com/drupaldiversity/administration/issues/132 @johnshortess @hanoii @hrod please take your awesome ideas there, thank you!
