### ISSUE TITLE
D&I Capacity Building Resources

### ISSUE THREAD

**Issue by adshill** [drupaldiversity/administration#40]
Work has already begun on [definitions](https://github.com/drupaldiversity/administration/issues/37), and there is a great list of resources [available and growing](https://drupaldiversity.github.io/resources/). I'm wondering if we can pull together some D&I "one-off" workshop ideas, and potentially a curriculum of various sessions that can be used to get Drupal agencies and organisations promoting and educating on DD&I from within. By encouraging this approach, more of the Drupal community will have insight before even arriving at events and while collaborating in the online spaces.

I assume the target audiences would be managers in smaller companies, and HR depts. of larger companies. We could also look to develop a directory of D&I experts - especially those that have Drupal knowledge/experience that can come into companies/orgs to help faciliate the sessions or work on other ideas.

I'm quite sure that in different communities there are resources tried and tested in this arena so I think much of the work will have been done, but to make them Drupal / FLOSS compatible or focussed would add real value and make them more "accessible". The resources could then be promoted through sessions at Drupal events and on D.o.

If people know of existing resources we could post them here and look to sprint on this at an event in the future or remotely. Do let me know if you're interested and I'll see what I can pull together from my sources!

**Comment by adshill** [comment]
Through work in a previous life we used this a lot: https://www.salto-youth.net/tools/toolbox/search/ however there is a LOT of sifting to do to find anything that would be relevant or adaptable to corporate environments, AND covers specifically D&I. If I find myself with a ton of time I might try doing some sifting.......

**Comment by adshill** [comment]
This is VERY interesting. TL;DR is that corporate diversity training doesn't actually work! BUT, when coupled with communication training and other diversity initiatives, it can work. Mostly relevant to bigger companies I think but its a good point that if doing work on diversity, there's probably some groundwork that needs to be done first. https://hbr.org/2012/03/diversity-training-doesnt-work

**Comment by adshill** [comment]
And something else interesting as a model: http://www.sodexo.com/home/corporate-responsibility/diversity-and-inclusion/how-we-act.html

Five areas of development:
- Diversity Training
- Promoting Mentoring
- Building Network Groups
- Partnerships for Diversity

Five pillars of Diversity:
- Gender
- Generations
- Disability
- Ethnical Origins
- LGBT

Could be useful to build on. I particularly like how mentoring and diversity are used together.

**Comment by rachellawson** [comment]
Don't have anything to add yet but definitely want to be involved

**Comment by cleverington** [comment]
omg. I don't know how I missed this, but I am fully in-favor of this issue.

Will add a relation to #44 as I feel like could have some serious co-working.

**Comment by sugaroverflow** [comment]
Thank you for your thoughts and suggestions!

We are working on this with our initiatives for creating slide decks people can use to talk about about DD&I - and with our events organizer packet. I'm going to close this issue for now, but we can reopen with we have more capacity to work on other things.
