### ISSUE TITLE
Create DrupalCon Photo Booth Filter & Background image for site

### ISSUE THREAD

**Issue by AlannaBurke** [drupaldiversity/administration#42]
So I don't forget to make the actual polaroid filter -- see #23 for the mockup. Also need to make a quick background image for the site that will host the photos, both to hand off to @mikemiles86 . 

Have been swamped and need to carve out an hour for this and will definitely forget if I don't ticket it! I may wait until i get the printer and can test to to officially decide on the filter, so I can see it in action.

**Comment by mikemiles86** [comment]
@AlannaBurke Just wondering when you think you'll be able to tackle this. I have people on my team getting the software pieces ready. Having these assets will be helpful.

**Comment by AlannaBurke** [comment]
I just got the printer today, so I'm going to start testing it out!

**Comment by AlannaBurke** [comment]
@mikemiles86 How about this for a background? Let me know what the dimensions should be if this doesn't work. 
[background](https://cloud.githubusercontent.com/assets/1540998/25028973/cfe885be-2086-11e7-8dae-964b62cc0136.png)
![ddi_bg](https://cloud.githubusercontent.com/assets/1540998/25028973/cfe885be-2086-11e7-8dae-964b62cc0136.png)

**Comment by AlannaBurke** [comment]
@mikemiles86 Here's the filter I came up with - since we're printing on actual polaroids, I didn't want to include the polaroid IN the filter. I do have a version with a polaroid frame, if there is a way to make both, one for uploading and one for printing. 
![instax-template](https://cloud.githubusercontent.com/assets/1540998/25031107/745f52e2-2098-11e7-919a-62e5ed7f0f94.png)
Here's what it looks like printed out:
![img_7276](https://cloud.githubusercontent.com/assets/1540998/25031154/d25d420a-2098-11e7-8247-2a0f47aa7f37.JPG)


I'm happy to accept suggestions as I'm not a designer!

**Comment by star-szr** [comment]
Looks awesome! You could maybe try using the font that was used for the sticker and banner and wordmark which I'm pretty confident is Source Sans Pro. Away from my computer for the weekend so it's hard to double check.

https://github.com/adobe-fonts/source-sans-pro/blob/master/README.md

**Comment by AlannaBurke** [comment]
@Cottser thank you! i have pitifully few fonts actually on my computer, so i was struggling there. i'll update it later today!

**Comment by mikemiles86** [comment]
@AlannaBurke great job with these!  The only feedback I have is that I think based on how the FotoOpp photo retrieval pages are currently built a repeating background image may work better.  But I think we can work with what you've provided by adding the rainbow stripe as background images to the header and footer and keeping the main content area with just a plain white background.

If you can provide these assets to me (once you have been able to update the font) I'll get them over to my developer who is working on building our FotoOpp instance.

**Comment by lpeabody** [comment]
@AlannaBurke These look fantastic! I think this will work okay. I'll be working with our FotoOpp app developers on Tuesday to make sure we can integrate these as is. I'll follow up then!

Also ping @mikemiles86

**Comment by star-szr** [comment]
Just a quick note to confirm that the font used for the stickers, banner, etc. is Source Sans Pro :)

**Comment by AlannaBurke** [comment]
@Cottser awesome, thanks! I'll update these today.

**Comment by AlannaBurke** [comment]
![instax](https://cloud.githubusercontent.com/assets/1540998/25097574/17bfe762-2373-11e7-854d-2a1e22608866.png)


Here's the updated template!
Let me know if you need anything else - I think using the rainbow bg for the header/footer with a white bg will look good.

**Comment by star-szr** [comment]
@AlannaBurke looks like the `@` sign and `y` on `@drupaldiversity` might be cut off a bit on the bottom. Cool though :)

**Comment by AlannaBurke** [comment]
@Cottser good catch - updated!

**Comment by star-szr** [comment]
Yay thanks :)

**Comment by star-szr** [comment]
@AlannaBurke thanks for designing this! It came up in this week's meeting that we might want a higher resolution version to try and work around some jaggedness we were seeing with the logo in fotoOpp. So here's a PNG from my vector re-creation of the template, and an SVG for fun too.
![photobooth template 4x](https://cloud.githubusercontent.com/assets/327943/25244315/25df2904-25ce-11e7-8bea-f112f5a00552.png)
[Photobooth Template.svg.txt](https://github.com/drupaldiversity/administration/files/944937/Photobooth.Template.svg.txt)

**Comment by AlannaBurke** [comment]
this is awesome and working nicely as far as i can tell!
