### ISSUE TITLE
Discuss photo policy for photo booth. 

### ISSUE THREAD

**Issue by AlannaBurke** [drupaldiversity/administration#43]
It was brought up that we should have a very concrete policy, especially to make things easier for volunteers. For example, "No signs in the photo," "No political slogans," "no slogans," etc.

Could someone maybe look for an example of this kind of thing? I don't feel the need to be too strict, and i don't anticipate problems but I do want a way to tell someone that their offensive shirt is not going to get a "this is what a drupalist looks like" label without getting into an argument. 

Also, given the current drama climate in the Drupal world, I could see a rabble rouser trying to make our lives difficult with this, so I'd rather have a crystal-clear policy.

**Comment by sparklingrobots** [comment]
The only event I've been at with something like this was the Minnesota State Fair, and the only [policy](http://minnesota.publicradio.org/events/minnesota-state-fair/photo-booth/) I can find online is not super relevant. 

Draft policy:

Thanks for participating in our photo booth.  We have a few rules of what can and can't be included in a photo: 
- Please, no logos, words or slogans of any kind (except the druplicon)--we're here to highlight the people of Drupal, after all! 
- All photos will be taken from the shoulders up, one person at a time. 
- We reserve the right not to post pictures for any reason. 

The last one could make some people angry but also is a backstop against somebody hijacking our super fun photo booth.   Also--group pictures. Yay or nay? I wrote it as nay but am flexible.

**Comment by penyaskito** [comment]
My 2 cents: group pictures could be cool too, as they can show the diversity of a team/group of friends. The third clause you wrote protects the DD&I team from any misbehaviour.

**Comment by AlannaBurke** [comment]
You know what, I think we can get away with one person at a time because these pictures are small, they're not regular polaroid sized. If we say that's why no group photos, and it's our policy, the end, we can probably avoid having to deal with anything. And yes, I think it's good to reserve the right not to post them just in case.

**Comment by sugaroverflow** [comment]
I think we should start with one person at a time and see how that goes.

**Comment by AlannaBurke** [comment]
this is done and printed!
