### ISSUE TITLE
Create onboarding documentation

### ISSUE THREAD

**Issue by hrod** [drupaldiversity/administration#44]
We currently have a page on our site dedicated to Initiatives and Get Involved: https://drupaldiversity.github.io/get-involved/

We would like to supplement that page with any information needed for newcomers so that we can effectively onboard them into the DD&I group.

**Comment by cleverington** [comment]
Instead of a supplemented page, why don't we create a Supplement?

We can use the same workflow and framework of the Event Organizer Packet to start drafting up a "Drupal D&I A11Y Packet".

You provide the content and I'll get the gitbook going.

Thoughts?

**Comment by cleverington** [comment]
Much of the info on the DCon talking points will probably be re-usable once we launch on supplemental content.

**Comment by hrod** [comment]
Great minds! That's exactly what I posted in the channel today :)

**Comment by sugaroverflow** [comment]
We've created a readme for the admin repo #99 , information about the teams and how to join them #88, and an introduction to the slack channel. Our social media policy #100 and core position values are in progress. And the tech team is working on a readme for website contributions https://github.com/drupaldiversity/drupaldiversity.github.io/pull/30

I think we're on our way to having some helpful onboarding documents. 
I'm closing this for now, but it may be reopened in the future if we need more documentation. 

Thank you for this issue! :)
