### ISSUE TITLE
Add a Code of Conduct for these projects, document via CODE_OF_CONDUCT.txt, README.txt

### ISSUE THREAD

**Issue by damienmckenna** [drupaldiversity/administration#45]
It's a little meta, but per a discussion in Slack it was pointed out that we should have a Code of Conduct for these projects. It would be worthwhile a) adding them to the repos in the form of a CODE_OF_CONDUCT.txt file, b) referencing them in each project's description and README.txt file. We can then use this to guide discussions of improving the document.

**Comment by drnikko** [comment]
We did discuss this here: https://github.com/drupaldiversity/administration/issues/13  if we want to use the same one someone can just submit PRs to all of our repos.

**Comment by damienmckenna** [comment]
Yeah, lets focus on the other issue. Thanks!
