### ISSUE TITLE
DC Booth talking points

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#46]
@eatings brought up yesterday that it might be a good idea to have some pre-set talking points ready so that we don't end up rehashing the details of LG/CWG/etc with each visitor.

Nothing fancy, just some key points that we can leave at the table for people.

**Comment by drnikko** [comment]
https://docs.google.com/document/d/1QdWI9AjvjS42n6jbfk2Vn92xD2zgZPeMxmkuz_s9hTI/edit

**Comment by AlannaBurke** [comment]
this was reviewed and printed out so I am going to close - we can write things down if needed!
