### ISSUE TITLE
Discuss opening a d.o issue to remove Drupal Association membership from Drupal.org profiles

### ISSUE THREAD

**Issue by frankmuse** [drupaldiversity/administration#50]
I think we should remove DA membership badges from Drupal user profiles. The reason for this is that some users may be socioeconomically disadvantaged and displaying a badge that shows how much they contributed to the DA or how much their employer contributed to the DA are both just indicators of their economic privilege.

I don't think a badge showing a user's economic privilege is a fair measurement of that user's value in the community.

**Comment by stephenpurkiss** [comment]
How about a free supporter level instead.

I'm a big believer in openbadges, I believe modules and so on could offer varying types. Then people could fill their profiles with all sorts of badges not necessarily aligned with money. But would that then offend people who haven't got badges? Or people who get offended by badges?

I do see your point a little, but removal I don't believe is the answer.

**Comment by frankmuse** [comment]
I like this idea of a "Free Supporter" level!

Or instead, just have open badges like you said! Maybe they need to be moderated first, but it would be great if you could give other members badges. Very democratic!

**Comment by stephenpurkiss** [comment]
Perhaps peer-reviewed but we'd probably just get back into the old project review issue situation so not sure that'd work. But say things like "pathauto best practices" or "views exposed filters" - maybe not to that detail but there's *so* much in Drupal I don't like the blanket accreditations they have at the moment. And of course when it comes to business then all sorts of other talents and experiences are needed.

But yes, openbadges FTW!

**Comment by YesCT** [comment]
Related: d.o profile meta issue https://www.drupal.org/node/2281763

**Comment by YesCT** [comment]
I recommend changing the title of this issue to something like:
Discuss opening a d.o issue to remove Drupal Association membership from Drupal.org profiles
or
Research and discuss the impact of economic indicators like DA membership badges on Drupal.org profiles

The issue to actually remove them would be on drupal.org.

**Comment by cleverington** [comment]
Updated topic based on YesCT's thought/approach.

My vote would be keeping the DA badge, but I fully agree with how cool it would be to include Open Badges as well.  Perhaps as a different / expanded recommendation/continuation for https://www.drupal.org/node/2203401 (which is about adding Open Badges to d.org profiles).

Drupal's motto is "Come for the Code, Stay for the Community". 

The Drupal Association is a _huge_ part of that Community and the driving force behind keeping DrupalCons and DrupalCamps running smoothly. In addition, drupal.org is part of the Organization which is Drupal.

By adding other options for sharing though, the DA becomes one of many.

**Comment by sugaroverflow** [comment]
I'm going to close this issue because I think it's out of our scope. 

If you'd still like to discuss the larger issue please feel free to open that. It sounds like this is more a discussion around: 
> How can we support people who can't afford DA membership 

Thank you for your thoughts! :)
