### ISSUE TITLE
Mentoring new or first-time speakers

### ISSUE THREAD

**Issue by sugaroverflow** [drupaldiversity/administration#51]
A few months ago, we came up with the wonderful #session-help channel in the Drupal slack to find and mentor new speakers for Drupalcon. 

I thought it would be a great idea for us to build on this at DC Baltimore and thought everyone would have some ideas. Maybe something like having people sign up as mentors or new-speakers-to-be and matching them up in some way?

**Comment by AlannaBurke** [comment]
As a first time speaker, what I would most like is for some experienced folks to come to sessions in case of troublemakers. My sessions aren't controversial (I don't think?) but I don't want to worry about it. I'll have my team members there, but not everyone will, and I think there are probably other first-time speakers who will rest easier knowing there are some folks in the audience ready to handle things should anything go south.

**Comment by heyrocker** [comment]
I'm happy to work with new speakers when future events are occurring!

**Comment by justAChris** [comment]
The issue of representation in the Drupal Watchdog magazine came up in the #diversity-inclusion channel today. Maybe this mentoring issue should expand to all forms of presentation (including articles and book publication), not just speaking.

**Comment by sugaroverflow** [comment]
@justAChris Thank you for your idea :)

I would like to keep this initiative within the scope of new speakers at Drupal events. I think keeping it specific will allow us to come up with more actionable items and get something small started and build upon it. 

 There's definitely value in mentoring on other forms of presentation - so maybe that's a discussion issue we can open for some brainstorming?

**Comment by justAChris** [comment]
@sugaroverflow Ha, I almost added "or we can open a separate issue for this" to my initial comment. Agree, focused issues to get actionable items. I've opened https://github.com/drupaldiversity/administration/issues/67 for discussion.

**Comment by sugaroverflow** [comment]
I'm closing this initiative for now because we haven't gotten a lot of traction _and_ I don't think we have the capacity to manage it. 

Anyone should feel to reopen if they would like to lead on this. Thank you for your work!
