### ISSUE TITLE
Photo Booth How-To!

### ISSUE THREAD

**Issue by AlannaBurke** [drupaldiversity/administration#53]
I will post the complete instructions here before DrupalCon, and will also print them out. Let's put any suggestions here, such as:

- Flip your badge around if it's visible in the photo

**Comment by sugaroverflow** [comment]
Let us know if you'd like to be tagged by username?

**Comment by AlannaBurke** [comment]
@sugaroverflow yes, this too - should this go in the privacy statement? https://github.com/drupaldiversity/administration/issues/29
I was thinking i could bring a stack of posts its, have people write down their handle, and we can stick it to the photo because we probably will not remember who is who.

**Comment by AlannaBurke** [comment]
I thought i had written out the entire how-to instructions this morning, but maybe I closed the tab? Unless the comment got deleted? argh, that's frustrating, I don't know where it went.

**Comment by sugaroverflow** [comment]
I think putting the instructions on the bottom of the privacy statement is a great idea. And the post-it username too! 

I saw the flip your badge on the doc. Maybe you can check the revisions or something?

**Comment by AlannaBurke** [comment]
Here is the printing how-to: https://docs.google.com/document/d/1DQ416dHLh4YgTSdCH4JHKm75dSFQpWP_BTanOpRZZBE/edit

and here are the instructions on taking photos, which needs info about fotoOpp, and i'm open to any suggestions here: https://docs.google.com/document/d/1SRiBYqxCY4UEQA6mlW2_42n6BjlO5TtGN9Kl_1LLzCM/edit

**Comment by star-szr** [comment]
What is the backdrop of the photos going to be? In other words, where would we be asking people to position themselves? I guess we might need to figure that out once we get the booth set up.

**Comment by AlannaBurke** [comment]
@Cottser I have no idea, i think we'll have to see when we get set up.

**Comment by drnikko** [comment]
Closing this because it's done and awesome!
