### ISSUE TITLE
Photo Booth Social Media/Marketing

### ISSUE THREAD

**Issue by AlannaBurke** [drupaldiversity/administration#54]
hashtags?
Start promoting and getting our photos this week!

**Comment by AlannaBurke** [comment]
If you want to put your photo up as a promo photo to keep our instagram from looking empty (and to test what the reaction will be) please post a selfie here! Or, if you will not be at DC Baltimore and want to participate in the photo booth this way :)

**Comment by AlannaBurke** [comment]
@drnikki if you want to share the instagram creds with me, i would be happy to take the lead on this.

**Comment by AlannaBurke** [comment]
Thoughts on hashtags?
#Drupal #diversity #ddi #inclusion #diversityinclusion #whatdrupallookslike #whatadrupalistlookslike

**Comment by rubyji** [comment]
Hmmm. #iamdrupal #drupalis #drupalist #drupaller

**Comment by rubyji** [comment]
#wearedrupal

**Comment by rubyji** [comment]
#wearedrupal

Does that feel exclusive like we're saying someone else _isn't_ Drupal? It could easily be co-opted/adopted by others, but that might not be a bad thing.

**Comment by AlannaBurke** [comment]
Hm, I see how it could be perceived that way. I definitely want to avoid
that right now. Would something like #thisisdrupal come across less 'us vs
them?' The message here is "we are all Drupal, look how diverse!" And not
"if you are not in a photo here, you are not Drupal." I want to make sure
our messaging is crystal clear.

**Comment by nicklewisatx** [comment]
@rubyji #WeAreDrupal has a lot of positive energy. I personally think it's a winner. 

(edit: people talk about drupal like it's a monolith.. it's actually a bunch of wonderful people, and I think this message reinforces that)

**Comment by AlannaBurke** [comment]
#diversityintech ?

**Comment by AlannaBurke** [comment]
I am okay with whatever the consensus is on hashtags. Also, if you'd like me to post your picture to start populating the instagram (I'd like to get at least a dozen up before DrupalCon), feel free to post it here, or email to `alanna` at `chromatichq.com` or PM on slack. We can always re-take at the booth, and if you're not going to be in Baltimore, this is a great way to participate!

**Comment by rubyji** [comment]
Here's one to use. Of course I'll do another one in Baltimore.

![rubysinreich-headshot-square](https://cloud.githubusercontent.com/assets/5465231/25151816/f8c39c0e-2454-11e7-8526-ee82ac47af22.jpeg)

**Comment by AlannaBurke** [comment]
@rubyji your picture is up! I put a few hashtags, we can always change them up :)

**Comment by sparklingrobots** [comment]
![dsc_2262](https://cloud.githubusercontent.com/assets/2217845/25191695/4a7a8496-24e5-11e7-90c7-c572ab189519.JPG)

**Comment by AlannaBurke** [comment]
adding #HumansOfDrupal!

**Comment by drnikko** [comment]
Closing this because we did a f'ing GREAT job!  There are still more photos to tweet, but I can do that from my laptop and then we have an open issue to put them all on our site [here](https://github.com/drupaldiversity/drupaldiversity.github.io/issues/21)
