### ISSUE TITLE
Accountability in online communities

### ISSUE THREAD

**Issue by mlncn** [drupaldiversity/administration#55]
Many communities are in need of approaches to achieving individual justice and perhaps conflict resolution where appeal to legal authorities is not possible or not likely to result in good outcomes for a community.  What forms of accountability are available and appropriate to online communities seeking to be inclusive of diverse members?

* Restorative justice "is a process to involve, to the extent possible, those who have a stake in an offense and to collectively identify and address harms, needs and obligations, in order to heal and put things right as possible." – Howard Zehr, PhD, The Little Book of Restorative Justice, 2002

* Transformative justice "seeks to provide people who experience violence with immediate safety and long-term healing and reparations while holding people who commit violence accountable within and by their communities. This accountability includes stopping immediate abuse, making a commitment to not engage in future abuse, and offering reparations for past abuse" - http://www.usprisonculture.com/blog/transformative-justice/

[Jack Aponte](https://twitter.com/jackaponte) referenced transformative justice and http://transformharm.tumblr.com/ (noting that it can also be applied in situations without specific victims) but they noted that "Restorative/transformative justice is HARD. It requires understandings of power & privilege & harm. It takes a long time" and "doesn't work so well in communities where power & privilege are ignored & where the people who cause harm are centered".  In keeping with such warnings, repeated frequently by advocates and practitioners, i haven't found examples of transformative or restorative justice applied to online communities, which are usually looser and have fewer mechanisms of accountability.

* Online Dispute Resolution, as a part of [Alternative Dispute Resolution](https://en.wikipedia.org/wiki/Alternative_dispute_resolution) (this latter claiming Restorative Justice as one of its own), despite being apparently well-established, is defined more vaguely.  [Leah Wing](http://odr.info/leah-wing/) (who happens to be a former professor of mine) has written on [ethical principles for ODR (PDF)](http://www.onlineresolution.com/wing.pdf), listing "accessibility, accountability, competence, confidentiality, empowerment, equality, fairness, honesty, impartiality, informed participation, innovation, integration, legal obligation, neutrality, protection from harm, security and transparency."

Transformative justice makes the point that as a community we must also be working on structural, societal injustice to apply its techniques to individuals: "Individual justice and collective liberation are equally important, mutually supportive, and fundamentally intertwined—the achievement of one is impossible without the achievement of the other." ([Toward Transformative Justice (PDF)](http://www.usprisonculture.com/blog/wp-content/uploads/2012/03/G5_Toward_Transformative_Justice.pdf))

Copy-paste of various links and definitions here: https://etherpad.net/p/restorative-justice-in-online-communities

**Comment by mlncn** [comment]
Probably the best distillation of a practical, transformation-seeking accountability approach comes from the prison abolition organization [Critical Resistance](http://criticalresistance.org/) which outlines five steps in their [Accountability Roadmap](http://www.usprisonculture.com/blog/wp-content/uploads/2012/03/accountabilityroadmap.pdf):

1. **Identifying Behaviors**:  The first step in a process is that a person must have an awareness and understanding of the actions and behaviors for which they are being called out. This is foundational and can sometimes take longer to accomplish than you might imagine.
2. **Accepting Harm Done**: Building on the understanding of what specific behaviors led them to this accountability process, the next step is to acknowledge in what ways these behaviors were harmful--even if harm wasn't their intention. This is the seed of one of the most frequent goals in a process: building empathy.
3. **Looking for Patterns**: Making Comprehensive change to prevent future assault requires broadening the focus beyond the isolated incident(s) that precipitated this process. This means identifying and naming the person's history of abusive/harmful actions and contextualizing these behaviors in their underlying assumptions and socialization.
4. **Unlearning Old Behaviors**: The process of breaking habits starts with identifying harmful dynamics and then deepens beyond naming to analysis and understanding. Gaining an awareness and determining the kinds of situations that trigger or enable abusive or harmful behaviors and then having clear strategies to avoid and diffuse the potential path for harm.
5. **Learning New Behaviors**: Building new positive/healing patterns of behavior goes hand in hand with breaking down the old harmful patterns.  One of the tools in this stage is role play, where a person can rehearse their consent practices, graceful acceptance of criticism, disclosure strategies, etc. Also important is becoming familiar with their resources to support positive and new behavior.

**Comment by mlncn** [comment]
Leah Wing recommends Danielle Citron's book, Hate Crimes in Cyberspace (2014) for "wonderful concrete suggestions for inclusion, safety, harassment prevention and response, etc."

**Comment by sugaroverflow** [comment]
I'm closing this because I don't see any discussion relating to the Drupal or our work as DD&I. The topic proposed is really broad and I would like us to discuss more specific issues with actionable items. 

Thank you for your thoughts! :)
