### ISSUE TITLE
File location?

### ISSUE THREAD

**Issue by legovaer** [drupaldiversity/administration#58]
In the end we want all of the documents we are creating to become available to the public, as we are doing here with GitHub. But I am not 100% convinced that this is the best way to move forward. GitHub is great, but people that are new to the project and maybe are not aware of GitHub might never find this documentation.

IMO: This information should get into Drupal.org as people who have concerns about D&I within our community are more likely to search this information on the drupal.org website.

There are several options;

- Keep it as-is
- Move it to Google Docs
- Move it to Drupal.org

**Comment by heyrocker** [comment]
When we say they should get onto drupal.org what are we really talking about?

- A set of documentation pages
- A DD&I project with associated issue queue and etc
- Something else?

Another concern I have in being on drupal.org is that it is explicitly the DA's territory. While that is not specifically something I fret over really, its worth considering how it impacts our independence.

In Baltimore we talked a bit about setting up our own website which has its own issues aka logins, permissions, hosting costs, etc. That said, I do think it is probably our best option and will allow for a solid editing experience and document management. (Does not explicitly have to be Drupal either.)

**Comment by cleverington** [comment]
From my approach, I think GitBook is a great way to leverage a 'produced' pieces of our content, and the way it is already built.

However, if we wanted to use different approaches, we can always convert it to ASCIIDOC (which Drupal.org's Documentation Team uses for a number of project), but I think the only supported modules for asciidoc are Drupal 7.

Alternatively, if we do not want to convert our existing content, there's always https://www.drupal.org/project/markdown , which has Drupal 7 and Drupal 8 versions.

Josh Koenig from Pantheon mentioned that Pantheon would be willing to host our site pro-bono (No quote can be provided, as it was a LONG time ago... Slack timeline-wise).

Either approach has its drawbacks, however, as currently our site is drupaldiversity.github.io. Migrating would either require registration of drupaldiversity.org (and the associated cost / maintenance planning) or hosting via something like drupaldiversity.pantheonsite.io 

My vote would be to separate by "project/area" (Organizer Packet, A11Y Packet, Contributors Packet, Web Team, Leadership Team, etc.).

Something like:

| Area / Project                       | Location                                      | Notes                                                                                                                                     |
|--------------------------------------|-----------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------|
| Event Organizer Packet               | GitHub                                        | We could also continuing using the Issue Queue on GitHub for changes and change requests                                                  |
| Diversity of the Web                 | GitHub                                        | This project is not quite closed, but is mostly in maintenance mode.                                                                      |
| Project Management                   | Asana? Trello? Shared and Locked Drupal Site? | I'll leave PM's to comment on the best approach for this one. I doubt JIRA would be 'in budget', but Trello leaves its own opportunities. |
| Mentorship                           | GitHub                                        | Same as Event Organizer's Packet                                                                                                          |
| Contributor's Packet                 | GitHub                                        | Same as Event Organizer's Packet                                                                                                          |
| A11Y Packet                          | GitHub                                        | Same as Event Organizer's Packet                                                                                                          |
| Web Team                             | Asana? Trello? Shared and Locked Drupal Site? | Something for collaboration on the Web **Site**, which allows for conversation without front-facing changes.                              |
| Leadership Team / Project Management | Asana? Trello? Shared and Locked Drupal Site? | I'll leave PM's to comment on the best approach for this one. I doubt JIRA would be 'in budget', but Trello leaves its own opportunities. |

**Comment by rubyji** [comment]
If we take Pantheon up on their offer to host we could pretty easily set up an Open Atrium site for project management.

**Comment by cleverington** [comment]
My understanding of the offer was more a public-facing site, would probably have to touch-base first on a closed Intranet-style site if we looked that direction.

**Comment by cleverington** [comment]
We talked about this topic fairly heavily in the Meeting today and the general consensus is to remain as we are within GitHub for at least the next quarter, but expand usage into:

- Start using GitHub "Projects", which can be by Repo (https://github.com/drupaldiversity/administration/projects) or by the entire project (https://github.com/orgs/drupaldiversity/projects)
- Create a new file at https://github.com/drupaldiversity/administration/tree/master/working-docs with a list of all active Google Docs / non-GitHub usage and a small description of each.

**Comment by sugaroverflow** [comment]
Linked this issue in #60 the general project management issue and closing this. (I want to merge the conversation to one place)
