### ISSUE TITLE
Create inclusion resource for organizers 

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#6]
Specific issues will be tracked in the packet repo, but this is here to indicate that we're working on it and it's timeline.

**Comment by cleverington** [comment]
@drnikki We created the Inclusion Resource for Organizers

Should we also think about creation an Inclusion Resource for Presenters/Speakers?

@cboyden's comments in Slack had me observing that the selection on Presenters is not the _only_ Diversity / Inclusion task needed.

We also need to educate Presenters / Speakers better on how to prepare / provide their information. 

For example, Microsoft PowerPoint has a built-in Accessibility Checker to allow screen readers to accurately interpret the document.

**Comment by drnikko** [comment]
I'm going to close this here since the work on the packet is in process. I think it's reasonable to include resources for speakers in that same packet - the organizers can (presumably) give it out to the speakers they select.
