### ISSUE TITLE
Account Security & Password Management

### ISSUE THREAD

**Issue by AlannaBurke** [drupaldiversity/administration#61]
As we develop teams, I imagine we will need to add more people to our social media accounts. We should make sure that we secure these accounts, think about any rules we need, and set up password management and anything else we need. @rubyji, if you're not overwhelmed, I thought this might be something you could head up, as you're both passionate and experienced.

**Comment by cleverington** [comment]
Very good observation, though we may want to consider putting together a [RACI](https://en.wikipedia.org/wiki/Responsibility_assignment_matrix) and (I may have missed this at DCon?) a confirmed Leadership Team first.

I know @drnikki and I both use Last Pass, so that would be my vote.

**Comment by sugaroverflow** [comment]
Linking to the notes on the leadership team discussions from DCon Baltimore, but we are probably going to need a virtual meeting to finalize these: https://github.com/drupaldiversity/administration/issues/28#issuecomment-298050141

**Comment by rubyji** [comment]
I can help with this, although I'm open to others. I know you have a lot of experience managing social media @AlannaBurke. 

Personally, I use 1Password now. But as far as Twitter goes we can add people to our account's "team" without giving away the password, so it doesn't need to be shared. Sadly, Instagram doesn't do this.

**Comment by drnikko** [comment]
https://www.drupal.org/project/diversity/issues/2929261
