### ISSUE TITLE
Create Github Issue Templates

### ISSUE THREAD

**Issue by AlannaBurke** [drupaldiversity/administration#63]
Create issue templates - start with agenda.

**Comment by sugaroverflow** [comment]
need actionable items section for issue template.

**Comment by sugaroverflow** [comment]
The meeting agenda seems to run okay as a bulleted list - but maybe issue creation needs a boilerplate. Were there ideas on this that you could share @AlannaBurke and I can maybe help you with the templating? 

Thanks!

**Comment by sugaroverflow** [comment]
We won't be needing Github issue templates since we are moving to d.o and will be using the standard issue summary template so closing this :) thank you @AlannaBurke !
