### ISSUE TITLE
Mentoring for published articles

### ISSUE THREAD

**Issue by justAChris** [drupaldiversity/administration#67]
Similar to https://github.com/drupaldiversity/administration/issues/51. 
There's an opportunity to mentor those new to writing articles for publications, blog posts and Drupal related books.
This is potentially challenging since the publication schedules vary throughout the year. However, we can follow a similar approach of aligning those interested with those who have had experience and success.

**Comment by sugaroverflow** [comment]
@justAChris I think this is a great idea! Maybe we could have office hours in the drupal slack, twitter, and/or IRC to offer people help with reviewing articles/blog posts/etc?

I imagine this will need a lot of volunteers and time. We could start with once every few months?

What else did you have in mind for this?

**Comment by sugaroverflow** [comment]
I'm closing this initiative for now because we haven't gotten a lot of traction _and_ I don't think we have the capacity to manage it. 

Anyone should feel to reopen if they would like to lead on this. Thank you for your work!
