### ISSUE TITLE
Feedback on, suggested changes to, evaluation of moderation guidelines (v1)

### ISSUE THREAD

**Issue by YesCT** [drupaldiversity/administration#68]
Related to https://github.com/drupaldiversity/administration/issues/34 
#diversity-inclusion channel moderation team

version 1 is up https://github.com/drupaldiversity/administration/wiki/%23diversity-inclusion-participation-and-moderation-guidelines-(v1)

Let's continue to iterate on the guidelines.

**Comment by YesCT** [comment]
Suggestions: 

1) change the title to participation and moderation guidelines

2) maybe in the future separate the two.
and/or
add headers with links to sections.

**Comment by cleverington** [comment]
So.... @sugaroverflow mentioned GitHub supports dropdowns.

Would go a **long** way to making the Guidelines more palatable.

## Example

<details>
<summary>Example Dropdown</summary>
This is some content
</details>

## Example Code
```
<details>
<summary>Example Dropdown</summary>
This is some content
</details>```

Source: https://gist.github.com/citrusui/07978f14b11adada364ff901e27c7f61

**Comment by cleverington** [comment]
Discussion in Slack led towards Anchor tags instead of dropdowns and/or child-pages as we **want** people to read the guidelines, not get lost in navigation..

**Comment by drnikko** [comment]
@YesCT You opened this issue and did a _ton_ of work getting it off the ground, so I want to make sure you've had a chance to review the new guidelines.

**Comment by drnikko** [comment]
we have an active moderation repo: https://github.com/drupaldiversity/moderation-guidance/issues so I'm closing this.  Folks can head over there (until that moves to d.o as well).
