### ISSUE TITLE
Gather people to be moderators in the slack channel

### ISSUE THREAD

**Issue by YesCT** [drupaldiversity/administration#69]
https://github.com/drupaldiversity/administration/issues/34 (#diversity-inclusion channel moderation team)
was doing a few things, 
generally discussing moderation
working on writing guidelines
collecting moderators

This issue is to (continue to) give a place for people to say "I'll be a moderator"

Potential list of moderators (please add yourself here, if editable, or make a comment below if volunteering):
@rubyji @AlannaBurke @YesCT @sugaroverflow @drnikki @lkopacz

**Comment by YesCT** [comment]
Related https://github.com/drupaldiversity/administration/issues/31 (Explicit leadership roles & appointments)

**Comment by gobinathm** [comment]
I would like to volunteer

**Comment by sparklingrobots** [comment]
This issue has been moved to drupal.org: https://www.drupal.org/project/diversity/issues/2929247

Tagging @drnikki !

**Comment by drnikko** [comment]
Thanks @sparklingrobots !! <3
