### ISSUE TITLE
Timeline / repo cleanup

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#7]
total administrivia, but need to do some housekeeping this week .

- go through old meeting notes and make sure it's all captured in an issue
- unify meeting notes and tasks (seems to make sense)
- update readme for new contributors with links and action items
- get that gdi-style tagging in place for the repo

**Comment by rubyji** [comment]
Also let's get the wiki list of resource links into a more prominent location.

**Comment by drnikko** [comment]
Thank you for finding this issue! I need to roll through and clean up some of these old ones. 

- I moved meeting notes to this repo
- i put the wiki links onto the website - https://drupaldiversity.github.io/resources/
- I added a get involved page and figure we can use that as an overall guide.  

It seems to make sense - for now - to just throw as much onto the website as possible so that it can be more accessible for those who don't (or don't want to) spent a ton of time in github, and until we figure out a better way.
