### ISSUE TITLE
Update MailChimp account info

### ISSUE THREAD

**Issue by rubyji** [drupaldiversity/administration#75]
I just joined our mailing list and I got the following confirmation page, which must have been set up when we were promoting the survey. I assume Nikki is currently the only person with access to change this. 

![screen shot 2017-05-10 at 2 39 51 pm](https://cloud.githubusercontent.com/assets/5465231/25915190/b03c05ac-358e-11e7-9327-de2150bad3bb.png)

**Comment by sugaroverflow** [comment]
pinging @drnikki could you close this issue when this is updated? :) thank you!

**Comment by drnikko** [comment]
Done!  Thanks for following up on this.
