### ISSUE TITLE
Reduce number of blues on the website

### ISSUE THREAD

**Issue by rubyji** [drupaldiversity/administration#76]
Can someone edit the callout to be the same blue as the links on our site (which is apparently #2a7ae2), the same blue as the logo (#42B6F0), or else some other color entirely? Also it would rock if the links just matched the logo as well.

![screen shot 2017-05-10 at 2 43 05 pm](https://cloud.githubusercontent.com/assets/5465231/25915335/316d8da8-358f-11e7-9a84-12b88a1ecb7f.png)

**Comment by cleverington** [comment]
Related:
https://github.com/drupaldiversity/administration/issues/85 

Apparently our version of Blue only goes with Black and pretty much just black.

I think we need to explore a third color. I was thinking something either purplish or pinkish.

**Comment by sugaroverflow** [comment]
Has this been resolved @cleverington ? If not, we should probably move this to the issue queue for drupaldiversity/drupaldiversity.github.io and close this (since the admin repo is moving to d.o).

**Comment by cleverington** [comment]
@sugaroverflow Though I apparently failed like... horrifically at commenting it, https://github.com/drupaldiversity/drupaldiversity.github.io/pull/37 actually resolved the initial issue.

The observed issue with our version of blue and "anything but black" in my previous comment could be opened on d.o. under a new/separate issue if PR 37 is approved.

(Adding a couple of notes to PR 37, though.)

**Comment by sugaroverflow** [comment]
Ohh, I see. Sorry that PR fell off my radar.

Putting PR 37 on my to-do list, moved your thoughts to this issue in the website queue: https://github.com/drupaldiversity/drupaldiversity.github.io/issues/40 and closing this :)

Thank you!
