### ISSUE TITLE
Create D&I Glossary

### ISSUE THREAD

**Issue by AlannaBurke** [drupaldiversity/administration#77]
Often we use terms, shortcuts, etc, that people who are not familiar to the space don't understand - let's create a glossary in the wiki to keep these terms as we think of them or as they come up, so that we can be more inclusive of newcomers to the diversity & inclusion space. Feel free to edit [the page](https://github.com/drupaldiversity/administration/wiki/Glossary) or add suggestions here.

Also, I just realized that the administration repo wiki may not be the best place for this kind of info - I'd love to create and maintain a wiki of public resources like this, but I'm not sure which repo it should go in, or if we should create a new one for this purpose. I don't think either option would be a barrier for entry, and a simple "resources" wiki may be useful in general. Thoughts?

**Comment by cleverington** [comment]
Both https://github.com/drupaldiversity/administration/issues/57 and #44 appear pertinent.

**Comment by jonpugh** [comment]
I think content like that's might be best under the resources section of the website?

**Comment by bradleyfields** [comment]
Wondering whether we recreate the content, refer to sources, or both.

Two source examples:
- [Human Rights Campaign's glossary of terms](http://www.hrc.org/resources/glossary-of-terms)
- [It's Pronounced Metrosexual's list of terms](http://itspronouncedmetrosexual.com/2013/01/a-comprehensive-list-of-lgbtq-term-definitions/)

If we found sources we trusted, there's value in acknowledging and supporting their work. Reason to create our own glossary would be if we had a unique way to present the same content on our platform.  But maybe our middle ground: We create a short list of the terms we think we use most often, but acknowledge there's a much wider discourse (refer to sources).

**Comment by bradleyfields** [comment]
Oh, and no matter what we choose, what do we think about creating a glossary bot for Slack (e.g., https://github.com/codeforamerica/glossary-bot)?

**Comment by damienmckenna** [comment]
During today's DD&I meeting it was mentioned that some people have difficulty with some of the terminology used, so this is of particular importance for the group.

**Comment by sacarney** [comment]
Perhaps we can scan for a list of words we use in the channel often, write our own definitions prominently so they are visible, and provide external resources for other words.

**Comment by sacarney** [comment]
Initial list to call out big in a glossary:

- Diversity vs Inclusion
- Privilege
- Systemic
- Institutional
- Intersectional
- "reverse racism"

What else in particular do we use frequently?

**Comment by sugaroverflow** [comment]
Since we are moving to drupal.org #145 @AlannaBurke would you like to copy this issue over and close this one? Thank you!

**Comment by drnikko** [comment]
https://www.drupal.org/project/diversity/issues/2929257
