### ISSUE TITLE
How can we make session selection as bias-free as possible?

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#8]
This selection process may be different for camps vs cons.   

There's a request for us to help disseminate the Druplacon Baltimore CFP [#9] to as diverse a group as possible to broaden the range of speakers selected.  

Some notes from the slack discussion: 
**Q: How can we get a broader range of people on the selection committees?**
- It just seems like people select presenters who they know or trust. They usually trust them because they’ve heard of them or their work, maybe they know people in common. I don’t think we can expect individuals to now make these judgements, so it would help to have individuals from different backgrounds who bring different networks and different experiences.

- the same problems that get in the way of under-represented communities proposing talks will also get in the way of people serving on the committee.

**Q: What other concerns should we address in a CFP?**
for underrepresented folks, cost is often an issue
for a number of reasons (personal finance, doubt about whether work will support them, etc.)

**Comment by rbartlettquotient** [comment]
This year at the Baltimore Camp we experimented- one person removed the identifying info (names, emails) from proposed sessions, and then the selection committee voted based on the description of each proposed session. This can present other problems, but can be useful to alleviate the problem of bias towards particular speakers.

**Comment by drnikko** [comment]
The official list of suggestions will live on this wiki page until we 'finalize' them as best we can

https://github.com/drupaldiversity/tasks/wiki/Specific-actions-for-reducing-speaker-selection-bias-and-creating-a-more-diverse-DrupalCon

**Comment by rpsu** [comment]
currently over here: https://github.com/drupaldiversity/tasks/blob/master/working-docs/speaker-selection-bias.md
