### ISSUE TITLE
Social media strategy & best practices

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#81]
This week, we need to finalize Twitter policies, access rules, and roles.  

I'd like to see a few things happen:
1. all tweets signed by the author (just initials are fine)
2. a page on the site that lists team members and helps people see the full information of authors of tweets
3. an internal document identifying who has access to the twitter account
4. a guideline for the interactions that we do (and choose not to do) from the group twitter account.

**Comment by cleverington** [comment]
Seems like it would be good as a directory and/or part of the RREADME.md for the Content Team's Repo.

**Comment by drnikko** [comment]
If they want their own repo, sure.  I think that team is still settling in.

**Comment by hrod** [comment]
So let's define the key components of a social media policy:

- Purpose (what are we attempting to achieve with our social media?)
- Audience (who are we trying to reach?)
- Content (what types of content do we post? How does that content support our mission? What do our audiences want to hear?)
- Tone (what is the tone of our communication? What types of interactions are encouraged/discouraged?)
- Personal accountability (do we disclose who is tweeting? Is that important if there's a unified message?)
- Dealing with Mistakes (if there's a grammar mistake, spelling error, factual error, mis-wording, how do we effectively deal with it?)
- Responding to Harassment (what steps do we take when someone is harassing the group?)

**Comment by bradleyfields** [comment]
@hrod A little while ago, we worked on https://github.com/drupaldiversity/drupaldiversity.github.io/issues/6 (re: a content strategy statement).

We could start there and find out how we could branch it for social platforms specifically. For instance, re: purpose, there's an annotation about "Not [being for] just anyone in tech," but focusing on our community's growth. There are also notes re: amplification, which something like Twitter would be great for.

**Comment by sugaroverflow** [comment]
collaboration going on in: http://bit.ly/ddi-socialmediapolicycollab

**Comment by sugaroverflow** [comment]
I opened a PR #100 with a draft :) please comment/give feedback/make changes/review. Thanks!

**Comment by sugaroverflow** [comment]
The first draft has been up for review for a few weeks now and I've made changes based on feedback from everyone. Closing this issue since PR #100 is ready for merge.
