### ISSUE TITLE
Coordinate with other D&I minded orgs to learn about how to handle harassment. 

### ISSUE THREAD

**Issue by hrod** [drupaldiversity/administration#82]
By reaching out to other orgs, we should be able to more effectively formulate a strategy for dealing with individuals who are engaging in harassing and bullying behavior targeting the DD&I initiative.

**Comment by sugaroverflow** [comment]
We're moving to drupal.org #145. @hrod if you'd still like to take this on, could you please create this issue in our d.o queue and close this one when you're done? https://www.drupal.org/project/issues/diversity

Thank you!

**Comment by drnikko** [comment]
I'm going to close this here - we can reopen, but I know for a fact that a cross-organization collaboratory is in the works and this is something they'll be including.
