### ISSUE TITLE
open indefinitely: Links to Read

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#83]
Until we can automate a way to store all links shared, we're dropping them here.

If you have permission to edit this issue, you can add them here, otherwise drop them as a comment on this ticket. 

- [It’s Time For The Left’s ‘Progressive’ Men To Start Listening](https://theestablishment.co/lets-talk-about-sexism-among-the-left-s-so-called-progressive-men-cda28d63c019)
- [The Stubborn Persistence of Confederate Monuments](https://www.theatlantic.com/politics/archive/2016/04/the-stubborn-persistence-of-confederate-monuments/479751/)
- [Good Black News](https://goodblacknews.org/)
- [What I Told My White Friend When He Asked For My Black Opinion On White Privilege](http://everydayfeminism.com/2016/08/told-white-friend-black-opinion/)
- [I'm A Trans Parent, & Here's Why Mother's Day Is So Tough For Me](https://www.romper.com/p/im-a-trans-parent-heres-why-mothers-day-is-so-tough-for-me-57233)
- [What does sponsorship look like?](http://larahogan.me/blog/what-sponsorship-looks-like/)
- [What Is Privilege?](https://www.buzzfeed.com/nicolaharvey/what-is-privilege)
- [Twitter thread on SV as colonialsm](https://twitter.com/_danilo/status/863423350185525249)
- [Question for male allies: what was the catalyst for your "ah-ha" moment regarding sexism in tech?](https://groups.drupal.org/node/419973)
- [Why are #PodcastsSoWhite?](https://www.cjr.org/the_feature/podcasts-diversity.php)
- [Project Include is our community for accelerating meaningful, enduring diversity and inclusion in the tech industry.](http://projectinclude.org)

- [So You've Got Yourself a Policy. Now What?](https://the-orbit.net/almostdiamonds/2014/04/10/so-youve-got-yourself-a-policy-now-what/)
- [The Eviction Economy](https://www.nytimes.com/2016/03/06/opinion/sunday/the-eviction-economy.html)
- [When We Talk About Cultural Appropriation, We’re Missing The Point
](https://theestablishment.co/when-we-talk-about-cultural-appropriation-were-missing-the-point-abe853ff3376)
- [Why Hackers Must Welcome Social Justice Advocates](https://medium.com/rx3-magazine/why-hackers-must-welcome-social-justice-advocates-1f8d7e216b00)

### Work/Life Balance
- [This is what work-life balance looks like at a company with 100% retention of moms](https://qz.com/806516/the-secret-to-patagonias-success-keeping-moms-and-onsite-child-care-and-paid-parental-leave/)
- [Rethinking the Work-Life Equation](https://www.nytimes.com/2016/02/28/magazine/rethinking-the-work-life-equation.html?_r=0)

### Workplace
- [EARFUL: ‘Another Round’ Producer On Why Diversity in Workplace is Essential](https://ww2.kqed.org/arts/2016/01/12/earful-another-round-producer-on-why-diversity-in-workplace-is-essential/)
- [Nurturing diversity at work and in your work](https://uxdesign.cc/nurturing-diversity-at-work-and-in-your-work-7d2b5571a9a4)
- [Your Company’s Culture is Who You Hire, Fire, & Promote](https://worldpositive.com/your-companys-culture-is-who-you-hire-fire-and-promote-c69f84902983)
- [Give opportunity, not charity: The case for neurodiversity in hiring](https://slackhq.com/give-opportunity-not-charity-the-case-for-neurodiversity-in-hiring-305e0bdf0a6)
- [Why I Won’t Make it Past Your Careers Page](https://medium.com/shenomads/why-i-wont-make-it-past-your-careers-page-e7408a67f813)
- [Taking mental health discussions off the bench at work]( https://slackhq.com/taking-mental-health-discussions-off-the-bench-at-work-d327bc606e44)
- [Why Solving Unconscious Bias in Sales Teams Boosts Diversity and Inclusion in Tech](https://medium.com/inside-the-salesforce-ecosystem/why-solving-unconscious-bias-in-sales-teams-boosts-diversity-and-inclusion-in-tech-7b52a4328628)

### Kids
- [Ways To Raise Inclusive Kids In The Tough Times Ahead](https://theestablishment.co/ways-to-raise-inclusive-kids-in-the-tough-times-ahead-46bc1a1d17cf)
- [Showing Up For Racial Justice (SURJ) Families](https://www.facebook.com/groups/814975055267531/)
- [How to talk to kids about racism](http://www.rageagainsttheminivan.com/2017/08/how-to-talk-to-kids-about-racism.html?m=0)

### Allies
- [Calling IN: A Less Disposable Way of Holding Each Other Accountable](http://www.bgdblog.org/2013/12/calling-less-disposable-way-holding-accountable/)
- [Calling In: A Quick Guide on When and How - Everyday Feminism](http://everydayfeminism.com/2015/01/guide-to-calling-in/)
- [9 Phrases Allies Can Say When Called Out Instead of Getting Defensive](http://everydayfeminism.com/2017/05/allies-say-this-instead-defensive/)

Great series by Vivianne Castillo on “Why Most Conversations in Tech About Diversity Are Bullshit — and What to Do About It”
1. [Why Most Conversations in Tech About Diversity Are Bullshit — and What to Do About It](https://uxdesign.cc/why-most-conversations-in-tech-about-diversity-are-bullshit-and-what-to-do-about-it-part-i-eca4962a3e7d) 
2. [The P-Word](https://uxdesign.cc/part-ii-why-most-conversations-in-tech-about-diversity-are-bullshit-and-what-to-do-about-it-6fbe7b0fd6fc)
3. [Greed Over Humanity](https://uxdesign.cc/part-iii-why-most-conversations-in-tech-about-diversity-are-bullshit-and-what-to-do-about-it-b1db8900fce7)
4. [Equality for All Women or Just White Women?](https://uxdesign.cc/part-iv-equality-for-all-women-or-just-white-women-8ee3f1b58)

**Comment by hrod** [comment]
- https://www.theatlantic.com/magazine/archive/2017/06/lolas-story/524490/

**Comment by ertiepie** [comment]
https://docs.google.com/spreadsheets/d/1SREuFbYYlwWdzlzvjAkALWPkBGGPUscaKzTYiYdvmTU/edit#gid=0
Public Google spreadsheet fed from a Slack I created (ddni.slack.com) to drop URLs into which then parses the pieces via a Zapier integration. The spreadsheet isn't super pretty at the moment, but I can tidy that up. I'd like to extend this to post the articles to a normal web page, blog style, but have the articles display pretty/expanded style with thumbnail, headline, url, subhead/intro, etc.

**Comment by cleverington** [comment]
Opening an issue on the Tech Team Board to theorycraft resolutions.

**Comment by seanr** [comment]
Here's one: "The Poverty of Privacy Rights": http://www.sup.org/books/title/?id=25115

**Comment by seanr** [comment]
This isn't directly related to our work, but it's a fascinating read (and a page turner) and will give you a sense of just how much of our constitution is rooted in the fight over slavery (hint: most of it):

https://www.amazon.com/More-Perfect-Union-William-Peters/dp/0517564505

**Comment by rubyji** [comment]
Great series by Vivianne Castillo on “Why Most Conversations in Tech About Diversity Are Bullshit — and What to Do About It”

1. [Why Most Conversations in Tech About Diversity Are Bullshit — and What to Do About It](https://uxdesign.cc/why-most-conversations-in-tech-about-diversity-are-bullshit-and-what-to-do-about-it-part-i-eca4962a3e7d) 
2. [The P-Word](https://uxdesign.cc/part-ii-why-most-conversations-in-tech-about-diversity-are-bullshit-and-what-to-do-about-it-6fbe7b0fd6fc)
3. [Greed Over Humanity](https://uxdesign.cc/part-iii-why-most-conversations-in-tech-about-diversity-are-bullshit-and-what-to-do-about-it-b1db8900fce7)
4. [Equality for All Women or Just White Women?](https://uxdesign.cc/part-iv-equality-for-all-women-or-just-white-women-8ee3f1b58)

**Comment by rubyji** [comment]
How “Good Intent” Undermines Diversity and Inclusion (Thanks, @catch56.) 
https://thebias.com/2017/09/26/how-good-intent-undermines-diversity-and-inclusion/

**Comment by rubyji** [comment]
I'll be working on adding these links to our resources page. Follow along at https://www.drupal.org/project/diversity/issues/2924467/

**Comment by rubyji** [comment]
More links I don't want to lose: 
https://protectourspaces.org/ 
https://www.hiremorewomenintech.com/
