### ISSUE TITLE
Update logo/header on the website to better match branding shown at DrupalCon

### ISSUE THREAD

**Issue by star-szr** [drupaldiversity/administration#84]
The assets for this are currently in this repo - wordmark/banner.

**Comment by keltique** [comment]
I've added a googlefonts call for Source sans pro to the head include, and adjusted the font stack in main.scss. it works locally to pull the typeface thru the site and in the site header.  I can generate a pull request as soon as it's set to accept one from me.

**Comment by drnikko** [comment]
@keltique I'm sorry that this got missed - if you have an open fork with work, we can merge that in.

**Comment by laughnan** [comment]
⚠️ Moved this thread to Drupal.org: https://www.drupal.org/project/diversity/issues/2929251

**Comment by drnikko** [comment]
Thanks @laughnan !! <3 <3
