### ISSUE TITLE
Ideas for a newsletter

### ISSUE THREAD

**Issue by sugaroverflow** [drupaldiversity/administration#86]
Collecting ideas for the newsletter.

Some thoughts from our team-content channel: 

>The great links that have been posted (in the channel) #83  would be amazing for a DD&I newsletter

>Taking a look at http://tinyletter.com/krotondo/archive - Ally as a Verb. I liked how they split it up into read, watch, listen, do, donate, etc. etc.

> I was thinking it would be fun to include maybe one tip on being an ally or I don't know, something actionable with each month. Something consistent yet unique. You think there would be enough content?

Thanks @cottser and @Hrod for the great idea!

**Comment by rubyji** [comment]
I think that almost anything that would be good in a newsletter would also make a good blog post.

**Comment by sugaroverflow** [comment]
Oh that gives me ideas!

- Teasers in the newsletter to the blog posts?
- Survey with the newsletter to see if people are interested to read a blog post on this -brief newsletter content piece-

**Comment by sugaroverflow** [comment]
From the Content team meeting 5/26
- We need a template for the newsletter
- Review process

**Comment by sugaroverflow** [comment]
- I think it would be beneficial to create the blog posts and share in the news-letter as an aggregation of blog posts, cool twitter-convos, and cool external resources.
- So anything that’s a good blog post and be included or teased in the newsletter. Anything good for the newsletter would also make a good blog post.
-  if we're going to use Mailchimp it would be easier to just use their own templates.

**Comment by sparklingrobots** [comment]
I find myself actually opening the links in the Trello newsletter (http://c.trellomail.com/deliveries/NDEzNTI6FwFX2wJkAAJzABefpiwaAVtjCYAmFTgYWTlsPAFtOjUwNjY0NgA). I think the summaries are really well written and compelling, and I don't feel overwhelmed by the quantity (Oh no when will I ever read ALL THESE GOOD LINKS?!) 

I also like the Ally as a Verb organizational scheme--maybe that structure (read/support/implement/etc) with a more miminal layout a la Trello? 

Are we using Mailchimp? If so, I have some ideas and could put together a template, but I can't get started until around mid July.

**Comment by cleverington** [comment]
Let us know if you'd like any assistance from the Tech Team for getting things configured and prepped for delivery.

I've heard whispers that MailChimp has a solid templating system, but we can definitely get some SASS and CSS going to prettify our content with the blues!

**Comment by sugaroverflow** [comment]
Since we're moving to drupal.org, I've migrated this issue here: https://www.drupal.org/project/diversity/issues/2923865
