### ISSUE TITLE
Update team dashboard content. 

### ISSUE THREAD

**Issue by sugaroverflow** [drupaldiversity/administration#88]
We can have the teams listed with brief explanations on the #87 Admin repo README and link off to team specific pages. 

I see each team page having a description of the team and links to the issue filters, project board, etc.

**Comment by sugaroverflow** [comment]
@cleverington @drnikki Do you think instead of creating a page for each team - it might be simpler to have some description and links to the project board for each team on the Admin repo Readme page #87 ?

**Comment by rubyji** [comment]
I think that people who want to know about our work but not necessarily participate in it might be interested in a short description of each team with a list of members.

Maybe instead of separate pages it could be one page with all of them and the description could be followed by a link to the project. Or maybe a link to a page that lists all the projects?

**Comment by cleverington** [comment]
I am all for Dashboards.

Something like:  ( http://www.tablesgenerator.com/markdown_tables )


| Team                                                                                                                                           | Description                                                                                                                                 | Current Focus                                                                                                                                                                                    |
|------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Leadership Team                                                                                                                                | The Vision and Mission setters of the group. They who lead all. The One ring... err.... wrong fiction...                                    | Supporting Team stabilization for newly created teams.                                                                                                                                           |
| [Content Team](https://github.com/drupaldiversity/administration/blob/master/working-docs/content-team.md "Content Team Homepage")             | The group whose true goal is the almighty **Content**. There's a saying _"Content is all"_ when communicating messages. This Team knows it. | Getting Social Media plans under control, creating effective communication between all Content Team members for creating scheduled/approved content / Public Relations style content, and more.  |
| [Technical Team](https://github.com/drupaldiversity/administration/blob/master/working-docs/teams/technical-team.md "Technical Team Homepage") | Somebody's gotta keep this ship duct-taped together.                                                                                        | Getting a monthly meeting scheduled and outlining needed tasks, both those to support the other teams and team-internal.                                                                         |
| [Design Team](https://github.com/drupaldiversity/administration/blob/master/working-docs/design-team.md "Design Team Homepage")                | Stuff about the Design Team                                                                                                                 | Stuff about what they are doing now.                                                                                                                                                             |
| [Moderation Team](https://github.com/drupaldiversity/administration/blob/master/working-docs/moderation-team.md "Moderation Team")             | Stuff about the Moderation Team                                                                                                             | Stuff about what they are doing now.                                                                                                                                                             |

**Comment by bradleyfields** [comment]
++ to the dashboard-ish idea.

Shorten the user flow, and we may not have enough content per team to justify individual pages for each anyway, yeah?

**Comment by cleverington** [comment]
Updated PR https://github.com/drupaldiversity/administration/pull/89 (for #87) with Team Dashboard details.

**Comment by sugaroverflow** [comment]
Thanks for making the dashboards cleverington! 

Renaming issue to add more content and update the "stuff here" portions of the readme (https://github.com/drupaldiversity/administration)

**Comment by rubyji** [comment]
OK, help a sister out: where do I see the dashboards?

**Comment by sugaroverflow** [comment]
@rubyji I'm working on updating the actual content -should get a PR up tonight, but they're here on the admin readme: https://github.com/drupaldiversity/administration/blob/master/README.md

Dashboard is just fancy way of saying tables :)

**Comment by sugaroverflow** [comment]
This is done.
