### ISSUE TITLE
Recruit individuals to submit at drupalcon baltimore

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/administration#9]
We need a list of specific individuals who meet the following criteria:
- have spoken at events before (local meetups, camps, other small presentations)
- have not spoken at a Drupalcon before

We'd like to refer these people to @eatings and @amandagonser for personal outreach.  

We don't need to list these individuals publically.  We just need to get people committed to recommending individuals.

**Comment by rubyji** [comment]
I can't be the bottom-liner, but I'd like to help with this.

**Comment by sugaroverflow** [comment]
This isn't for specific individuals, but to find more people who are interested. How about announcing this at local meetups? I think it would reach a lot of people that way and meetups are a great place to get session help, too.

**Comment by drnikko** [comment]
@sugaroverflow definitely - I'll announce it in the camp organizer slack channel.  My guess is that many of them are also involved at the local meetup level.

**Comment by drnikko** [comment]
Closing because call for submissions is also closed.
