### ISSUE TITLE
Content team meeting agenda for May 26

### ISSUE THREAD

**Issue by sugaroverflow** [drupaldiversity/administration#93]
The Content team is having their first meeting on May 26 at 12:00 PM EST (9:00 PST) in the #diversity-inclusion channel. 

Agenda Items: 
- Welcome to the Content team
- http://bit.ly/ddi-content-project-board
- Social Media
    - Choosing a twitter scheduling service
    - Drafting our Social Media policy
- Newsletter
   - brainstorming/planning 
-  Content
   - Blog posts for the website
   - DD&I Glossary 
- Admin things: 
        - Dashboard for the teams
        - Landing page for the sites working docs

**Comment by cleverington** [comment]
On the 'landing page for the site's working docs', that might be a great location to outline not only the content (via dashboard), but the infrastructure as well.

Something along the lines of....

```
- working-docs/
  - content-team/
    - presentations.md <-- Make in Google Docs and track via 'Share' links?
    - verbiage-guidelines.md
  - technical-team/
    - github-pages-instructions

```

**Comment by sugaroverflow** [comment]
Thank you everyone for attending the meeting !
